$axure.loadCurrentPage({
  "url":"流程说明.html",
  "generationDate":new Date(1462500150110.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"407f76a072834ccf967d1ad4fc5ddb92",
    "type":"Axure:Page",
    "name":"流程说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1e44322b0f984e93a86c0b0050311509",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":30},
            "size":{
              "width":1350,
              "height":1490},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b5c247664044f11a301cc8a59da4b38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":30},
                "size":{
                  "width":1350,
                  "height":1490},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u0.png"}},
{
          "id":"2b81f50e85594250b0d5dfac10c982df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":30},
            "size":{
              "width":1350,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e65aec9ab5b5445d81135a18cc3fad87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":30},
                "size":{
                  "width":1350,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u2.png"}},
{
          "id":"4aa9307bd9e4441d9880bf6b756be091",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":570,
              "y":46},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caeb77ffc9e44c2d89240116e14e2789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":570,
                  "y":46},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ef590cb9ad94829a865e06bbe8fe587",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":80},
            "size":{
              "width":1350,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b30dfec824be455dbe2dbab42c4ee400",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":80},
                "size":{
                  "width":1350,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u6.png"}},
{
          "id":"5c96bcabc6654a77ab37a357b1d4789c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":505,
              "y":94},
            "size":{
              "width":10,
              "height":1426},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明/u8_line.png"}},
{
          "id":"c22356de6fb64ee4aa39cfe1e1a2362a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":60,
              "y":96},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a253592ab0e41908da3c0f12f030707",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":60,
                  "y":96},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e4c38c50b0e42a9b77f1bfa633ed319",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":580,
              "y":96},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c833843cd6984777849d97641f52229b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":580,
                  "y":96},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bf117a2921249e2a3840bd981b4c574",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":120,
              "y":150},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17bd3074a1f94277bffb0844d822c160",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":120,
                  "y":150},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u13.png"}},
{
          "id":"4ce7c4c7c7724402b43cfaa3cd67d993",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":90,
              "y":250},
            "size":{
              "width":150,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e10da5ec59f64be498fd08c5b969f78e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":250},
                "size":{
                  "width":150,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u15.png"}},
{
          "id":"fc5015f7b9d74760aa835a7a3a140913",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":190},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9cc655caf19405f9b581655c72c1347",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":190},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"834c97138985490d9960b21a7a07d87e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":780,
              "y":250},
            "size":{
              "width":150,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e30af8c8a22a46fe849d1c923672067e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":780,
                  "y":250},
                "size":{
                  "width":150,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u15.png"}},
{
          "id":"0bfd06c5690449dd98288ff89e916bee",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":275},
            "size":{
              "width":540,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明/u21_end.png",
            "line~":"images/流程说明/u21_line.png"}},
{
          "id":"238394be91c64f79849eeb2ee40e561f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":450,
              "y":260},
            "size":{
              "width":140,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10e48520c175437a861550bb91c2d1fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":450,
                  "y":260},
                "size":{
                  "width":140,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u22.png"}},
{
          "id":"d49a50246abf450e856a0f3406ae4977",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":90,
              "y":450},
            "size":{
              "width":150,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64ef1dd596e94b8b8b336e8287224adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":90,
                  "y":450},
                "size":{
                  "width":150,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u15.png"}},
{
          "id":"e99cdafc54fb440aaaa4dbe3da762859",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":855,
              "y":310},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23050c1adc19499e9e70d23126b11100",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":855,
                  "y":310},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}]},
{
          "id":"d912bc102753496481b1c64dc5d53add",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":590},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d33c0567c0d4d47b2a62dd90e786dd5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":590},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"d6781840727b4bcd8433494fb97ba6ba",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":510},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23a5790ae37a481092a789417844a6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":510},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"7d4b45a69285455ca5c8e203ea5f1964",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":720},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"392fe9b1612c4d198bdaa947b2f4977d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":720},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"a138bb21a88c42a99e338b2881926d45",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":650},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a083bf12eadd49a0865fd52ddcacafb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":650},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"926b689e19514876b014986948b3169e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":780,
              "y":720},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adc1377a6d7047cba4733ca922bb80c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":780,
                  "y":720},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"948c3e896819450395923f91b498fcca",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":750},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41175aa5a8ac4577961deaa124aac551",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":750},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"d2a4ac51577a415a9b6d12f7811fe532",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":780,
              "y":840},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7f6a70d7f2e4e06aa786592912a13fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":780,
                  "y":840},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"3102c1086ba94afdad6556c206452b20",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":855,
              "y":780},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dbd5810b149466fa6d6c77d4e6c9cc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":855,
                  "y":780},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"769d5f05a8874973938ee365b58a5ed2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":840},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1518b6e1ef074d9b9818fb5931b0bcaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":840},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"c77a8751f446456abd472cb1fc7b543a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":870},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3a9f9c4f5e64a859dd22d80f5601bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":870},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"db69d449c3c145639abf21cae8acca8f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":90,
              "y":980},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee1b3a202e944846a76a62507bc890d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":90,
                  "y":980},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"7d448c73f07e451ea1a0dce9ed1f23f9",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":900},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dc416b48d744476a49a0db7f58c164e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":900},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"2d17691c11364e1688fba0ea32aafc18",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":980,
              "y":94},
            "size":{
              "width":10,
              "height":1426},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明/u8_line.png"}},
{
          "id":"084410bcb6ae45f5bf64c82ac4a20bce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":1070,
              "y":96},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"649fca09bbfb420b869cf4ab616e5919",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":1070,
                  "y":96},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f14b65d4b09642b68fb8aaf4d670a373",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1130,
              "y":980},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eff670187214edba1af2911ddab9f2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1130,
                  "y":980},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"5374243717d04c5e86c2524efd482220",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":1005},
            "size":{
              "width":890,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明/u57_end.png",
            "line~":"images/流程说明/u57_line.png"}},
{
          "id":"8a6bb993ae564a2bb8b7f39a4edee6e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1200},
            "size":{
              "width":465,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"184caf5aa3174be8800fbb2fb6509fb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1200},
                "size":{
                  "width":465,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"02c7d7be4dc14631ae03be8e7c6e3b33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":50,
              "y":1221},
            "size":{
              "width":455,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d96d9cd9cad24dce8a31b38fc18d7794",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":50,
                  "y":1221},
                "size":{
                  "width":455,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04dcfcfad52b4a9188c029a33f095b3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":50,
              "y":1270},
            "size":{
              "width":455,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f04e415b68547a4b505c9e3d182b90d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":50,
                  "y":1270},
                "size":{
                  "width":455,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6b0fbab0e4e4861b1012bcaefdd325b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":1200},
            "size":{
              "width":465,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"463b1eb8cef4439186b6c3070af45d6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":1200},
                "size":{
                  "width":465,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"47e2bd0feef84156b9a6417728f34c40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":520,
              "y":1261},
            "size":{
              "width":455,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c38e932a49ef4bff95efa6cebf1d68f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":520,
                  "y":1261},
                "size":{
                  "width":455,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1e44322b0f984e93a86c0b0050311509":{
      "scriptId":"u0"},
    "8b5c247664044f11a301cc8a59da4b38":{
      "scriptId":"u1"},
    "2b81f50e85594250b0d5dfac10c982df":{
      "scriptId":"u2"},
    "e65aec9ab5b5445d81135a18cc3fad87":{
      "scriptId":"u3"},
    "4aa9307bd9e4441d9880bf6b756be091":{
      "scriptId":"u4"},
    "caeb77ffc9e44c2d89240116e14e2789":{
      "scriptId":"u5"},
    "8ef590cb9ad94829a865e06bbe8fe587":{
      "scriptId":"u6"},
    "b30dfec824be455dbe2dbab42c4ee400":{
      "scriptId":"u7"},
    "5c96bcabc6654a77ab37a357b1d4789c":{
      "scriptId":"u8"},
    "c22356de6fb64ee4aa39cfe1e1a2362a":{
      "scriptId":"u9"},
    "2a253592ab0e41908da3c0f12f030707":{
      "scriptId":"u10"},
    "1e4c38c50b0e42a9b77f1bfa633ed319":{
      "scriptId":"u11"},
    "c833843cd6984777849d97641f52229b":{
      "scriptId":"u12"},
    "2bf117a2921249e2a3840bd981b4c574":{
      "scriptId":"u13"},
    "17bd3074a1f94277bffb0844d822c160":{
      "scriptId":"u14"},
    "4ce7c4c7c7724402b43cfaa3cd67d993":{
      "scriptId":"u15"},
    "e10da5ec59f64be498fd08c5b969f78e":{
      "scriptId":"u16"},
    "fc5015f7b9d74760aa835a7a3a140913":{
      "scriptId":"u17"},
    "a9cc655caf19405f9b581655c72c1347":{
      "scriptId":"u18"},
    "834c97138985490d9960b21a7a07d87e":{
      "scriptId":"u19"},
    "e30af8c8a22a46fe849d1c923672067e":{
      "scriptId":"u20"},
    "0bfd06c5690449dd98288ff89e916bee":{
      "scriptId":"u21"},
    "238394be91c64f79849eeb2ee40e561f":{
      "scriptId":"u22"},
    "10e48520c175437a861550bb91c2d1fb":{
      "scriptId":"u23"},
    "d49a50246abf450e856a0f3406ae4977":{
      "scriptId":"u24"},
    "64ef1dd596e94b8b8b336e8287224adb":{
      "scriptId":"u25"},
    "e99cdafc54fb440aaaa4dbe3da762859":{
      "scriptId":"u26"},
    "23050c1adc19499e9e70d23126b11100":{
      "scriptId":"u27"},
    "d912bc102753496481b1c64dc5d53add":{
      "scriptId":"u28"},
    "4d33c0567c0d4d47b2a62dd90e786dd5":{
      "scriptId":"u29"},
    "d6781840727b4bcd8433494fb97ba6ba":{
      "scriptId":"u30"},
    "23a5790ae37a481092a789417844a6cf":{
      "scriptId":"u31"},
    "7d4b45a69285455ca5c8e203ea5f1964":{
      "scriptId":"u32"},
    "392fe9b1612c4d198bdaa947b2f4977d":{
      "scriptId":"u33"},
    "a138bb21a88c42a99e338b2881926d45":{
      "scriptId":"u34"},
    "a083bf12eadd49a0865fd52ddcacafb5":{
      "scriptId":"u35"},
    "926b689e19514876b014986948b3169e":{
      "scriptId":"u36"},
    "adc1377a6d7047cba4733ca922bb80c4":{
      "scriptId":"u37"},
    "948c3e896819450395923f91b498fcca":{
      "scriptId":"u38"},
    "41175aa5a8ac4577961deaa124aac551":{
      "scriptId":"u39"},
    "d2a4ac51577a415a9b6d12f7811fe532":{
      "scriptId":"u40"},
    "f7f6a70d7f2e4e06aa786592912a13fd":{
      "scriptId":"u41"},
    "3102c1086ba94afdad6556c206452b20":{
      "scriptId":"u42"},
    "0dbd5810b149466fa6d6c77d4e6c9cc7":{
      "scriptId":"u43"},
    "769d5f05a8874973938ee365b58a5ed2":{
      "scriptId":"u44"},
    "1518b6e1ef074d9b9818fb5931b0bcaa":{
      "scriptId":"u45"},
    "c77a8751f446456abd472cb1fc7b543a":{
      "scriptId":"u46"},
    "f3a9f9c4f5e64a859dd22d80f5601bdf":{
      "scriptId":"u47"},
    "db69d449c3c145639abf21cae8acca8f":{
      "scriptId":"u48"},
    "ee1b3a202e944846a76a62507bc890d7":{
      "scriptId":"u49"},
    "7d448c73f07e451ea1a0dce9ed1f23f9":{
      "scriptId":"u50"},
    "4dc416b48d744476a49a0db7f58c164e":{
      "scriptId":"u51"},
    "2d17691c11364e1688fba0ea32aafc18":{
      "scriptId":"u52"},
    "084410bcb6ae45f5bf64c82ac4a20bce":{
      "scriptId":"u53"},
    "649fca09bbfb420b869cf4ab616e5919":{
      "scriptId":"u54"},
    "f14b65d4b09642b68fb8aaf4d670a373":{
      "scriptId":"u55"},
    "7eff670187214edba1af2911ddab9f2c":{
      "scriptId":"u56"},
    "5374243717d04c5e86c2524efd482220":{
      "scriptId":"u57"},
    "8a6bb993ae564a2bb8b7f39a4edee6e2":{
      "scriptId":"u58"},
    "184caf5aa3174be8800fbb2fb6509fb9":{
      "scriptId":"u59"},
    "02c7d7be4dc14631ae03be8e7c6e3b33":{
      "scriptId":"u60"},
    "d96d9cd9cad24dce8a31b38fc18d7794":{
      "scriptId":"u61"},
    "04dcfcfad52b4a9188c029a33f095b3c":{
      "scriptId":"u62"},
    "7f04e415b68547a4b505c9e3d182b90d":{
      "scriptId":"u63"},
    "e6b0fbab0e4e4861b1012bcaefdd325b":{
      "scriptId":"u64"},
    "463b1eb8cef4439186b6c3070af45d6b":{
      "scriptId":"u65"},
    "47e2bd0feef84156b9a6417728f34c40":{
      "scriptId":"u66"},
    "c38e932a49ef4bff95efa6cebf1d68f9":{
      "scriptId":"u67"}}});