$axure.loadCurrentPage({
  "url":"流程说明_2.html",
  "generationDate":new Date(1462500153607.4),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"34343b69008b404580774f8b22b90287",
    "type":"Axure:Page",
    "name":"流程说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8ba894d9578d4ba9a5e6e35911265376",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":1530,
              "height":1670},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60a090f54c914812b46c8c788240b041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":1530,
                  "height":1670},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_2/u0.png"}},
{
          "id":"3e132a17d028417bba038e075e5c92ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":20},
            "size":{
              "width":1530,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0293ea4ef30b4bed8a6008ea7348f3d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":20},
                "size":{
                  "width":1530,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_2/u2.png"}},
{
          "id":"c69b8d93cc7f4ba38c01a647a20a9c79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":570,
              "y":36},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fc0ac51d4fc4fd2aae3a03ac7743a41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":570,
                  "y":36},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ce283d815f94a2d8b1d7fb836fed607",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":70},
            "size":{
              "width":1530,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"043f3eddd6c349089ef3473021b7b48e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":70},
                "size":{
                  "width":1530,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_2/u6.png"}},
{
          "id":"df8f7cb0196d4bdf9974811779ea1ae9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":82},
            "size":{
              "width":10,
              "height":1608},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_2/u8_line.png"}},
{
          "id":"2e1fbcade0384b8d8858e8992efe795e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":86},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a3188a7266243d496c735bef2073b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":86},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7ee3bc4f8eb497abe2394e5705f371f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":640,
              "y":86},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3922b18476c4436fac92342bd9a3a22b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":640,
                  "y":86},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d596d63255a498e8dce4d5968241289",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":80,
              "y":140},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45762b4a4b004acb9d2c2523d526743f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":80,
                  "y":140},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u13.png"}},
{
          "id":"768c0eb35ebb4b399351304b402901d8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":50,
              "y":330},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61e50636f8e14213abd933ac91c23187",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":50,
                  "y":330},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"67643ac4e2cd4233b59ee64fb79d44ef",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3aa888711b5740d3b2a8ed608e925f63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"235527dfd02f43a38294889b47669156",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1150,
              "y":80},
            "size":{
              "width":10,
              "height":1608},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_2/u8_line.png"}},
{
          "id":"7cc07dff9a4e4908befab866f5fe13a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":1210,
              "y":86},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb81489cd18146f5a20685d70ec877d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":1210,
                  "y":86},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3410aeb6365346b0a18fcf7978cd739f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":640,
              "y":150},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08b797fc99014d4a8ac8072de0394044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":640,
                  "y":150},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"dafc9860bdaf4aa69861b42fab0b2394",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":630,
              "y":500},
            "size":{
              "width":150,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8989590e167b457ab2e1b40b492d081b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":500},
                "size":{
                  "width":150,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u15.png"}},
{
          "id":"a619b9e4c40b433eb89ce73cc47948c2",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":631,
              "y":700},
            "size":{
              "width":150,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"654b536676384cdf81e5b6d21174b0f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":631,
                  "y":700},
                "size":{
                  "width":150,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u26.png"}},
{
          "id":"d9c531a88ab5416d979cec25655b2ad8",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":472,
              "y":850},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb130d663b1e4f329574d2eb15ced1cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":472,
                  "y":850},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"0fa5613ea73c4ab19c6ec20320af934d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":50,
              "y":490},
            "size":{
              "width":150,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517f005d4206407cb3cbfdb5736ac076",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":50,
                  "y":490},
                "size":{
                  "width":150,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u30.png"}},
{
          "id":"d8a8d536d8da4301b1e70836d97aaaa2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":210},
            "size":{
              "width":10,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u32_line.png"}},
{
          "id":"2fe06d35e1ae433eb6c645c9f2e4e5f1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":480,
              "y":700},
            "size":{
              "width":134,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0ccf9dcd41c42b0b914cd88a63e42e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":480,
                  "y":700},
                "size":{
                  "width":134,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u33.png"}},
{
          "id":"0fe1f128967a483abccf715d4e4515ba",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":390},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d99b128954de4d64853395bf27ce2a94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":390},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"7f645b23c64e481a9ba3847110d8b4cb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":640,
              "y":270},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6491547a66149eba2283921e665ec60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":640,
                  "y":270},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"5aafb3362edd449d93d93356486ceb20",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":266},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1843091baa15421aa2a37438ba7679b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":266},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u39.png"}},
{
          "id":"9887978bfdfc46c8a7dad8bfaa9e6510",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":295},
            "size":{
              "width":260,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/流程说明_1/u41_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u41_line.png"}},
{
          "id":"85e40bb7d3c14ec2b6b2c979daf0a626",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":420,
              "y":280},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42bdfa40fa9d4db2b62b8d2585743152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":420,
                  "y":280},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u42.png"}},
{
          "id":"60a292dd443040b59ab0602ebfaf8927",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":264},
            "size":{
              "width":10,
              "height":391},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u44_line.png"}},
{
          "id":"5b6d3acc16424338ba7b4e079763e1d8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":336},
            "size":{
              "width":10,
              "height":124},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u45_line.png"}},
{
          "id":"871040723cba4be89d028cf0f6469b16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":422,
              "y":440},
            "size":{
              "width":85,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67c92c16648743fbbac84d9c098b821d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":422,
                  "y":440},
                "size":{
                  "width":85,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u46.png"}},
{
          "id":"f191dc1c48514ea58d3d1ed9b5e1247a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":701,
              "y":458},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u48_line.png"}},
{
          "id":"fab7afe95624406584dedaf19be90964",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":525},
            "size":{
              "width":430,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/流程说明_1/u41_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u49_line.png"}},
{
          "id":"0df0e69b4ab348bbbf0339796be969a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":385,
              "y":510},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f79bbf83d14f4bbc63c772ecaaa013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":385,
                  "y":510},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u50.png"}},
{
          "id":"fd301f75d50f4b1da41b2ab8b5ff7979",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":570},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5769aef921c744f6aabb7f559450592d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":570},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"45d9c7d4df054a3497a8686cdd1d39e7",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":560},
            "size":{
              "width":10,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u54_line.png"}},
{
          "id":"5385c971ebe14cd2b137942b9d82b97a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":644,
              "y":610},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6da76fe633f4e4399ea41bb8560c032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":644,
                  "y":610},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u55.png"}},
{
          "id":"041e91f5b55c43dc9b559c1da564d41c",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":770},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0efc689fde141d689dfceaf05be2df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":770},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"0e6cb93cee194a48b9efbe26f80dc190",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":960},
            "size":{
              "width":150,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e951474794944a4b806da03ed1ff883",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":960},
                "size":{
                  "width":150,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u59.png"}},
{
          "id":"4f57a03c6687451d8a4320817d06eb9e",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":844},
            "size":{
              "width":10,
              "height":302},
            "rotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u61_line.png"}},
{
          "id":"a5dc9847ecb444cdbcaaf3611c341bba",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":701,
              "y":770},
            "size":{
              "width":10,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u62_line.png"}},
{
          "id":"318b4d9c4d504e19917c5738a3f3d34a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":560,
              "y":975},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9ecf90f8a674d0b999c177ca91c4534",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":560,
                  "y":975},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u55.png"}},
{
          "id":"5edf49cec7644e8390ce274bef0d5672",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":880},
            "size":{
              "width":10,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u65_line.png"}},
{
          "id":"f45c124907964dcc8c5cda78742c14a8",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":809},
            "size":{
              "width":10,
              "height":142},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u66_line.png"}},
{
          "id":"f6280164ffdc4ee68174aedaa3924dbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":298,
              "y":900},
            "size":{
              "width":75,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29db337932ae425f890c43436ca378b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":298,
                  "y":900},
                "size":{
                  "width":75,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u67.png"}},
{
          "id":"a329f66663b1450499ad9fafe3d7d80c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1283,
              "y":150},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8e93e6553034dabb79a7794cd60dded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1283,
                  "y":150},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u69.png"}},
{
          "id":"c0ab3151e0cb42949bccc6d1407948c9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1255,
              "y":310},
            "size":{
              "width":155,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e65b4f4a184344e8b7f5b65b8d7a6b1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1255,
                  "y":310},
                "size":{
                  "width":155,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u71.png"}},
{
          "id":"f4985dd8c04241deb9fe658e128ec614",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1333,
              "y":190},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93776499e1074fbe8f6ef44bc91b5fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1333,
                  "y":190},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"ea1cbaa108534b6d91ed04b4343bb385",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1255,
              "y":820},
            "size":{
              "width":155,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f928f03e4bec4943ad6669988de92055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1255,
                  "y":820},
                "size":{
                  "width":155,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u71.png"}},
{
          "id":"54af874ccef04d2da12a443d95898573",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":880,
              "y":820},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbe8c341e9644e98901b7065ee1d54a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":880,
                  "y":820},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"375c7d32b27245b08af77d4267cd79f9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1260,
              "y":1030},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c64013ef4a4430ca07615b90d7f18b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1260,
                  "y":1030},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"8f6c0b2ab2be481bbc0271a7d26f48b7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":955,
              "y":880},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccd56426ee6d4ad18491a0456aa6daf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":955,
                  "y":880},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"cac499fd51144bcbbb761a2ce534eaea",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1260,
              "y":1230},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d9a82234bca4a01931f7b76b77b0433",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1260,
                  "y":1230},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"f21708b244ba4bc29e6ba7497f8f8eb7",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1335,
              "y":1090},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4cc2cde20c4468d8aa7f530731e0a22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1335,
                  "y":1090},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"e2e9666f911d40ff8b757c8574418835",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":130,
              "y":1229},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd91206e56441e296b4fc15aef548ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":130,
                  "y":1229},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"2130f154af234a949fe3b0b6707b7fd5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":1255,
              "y":490},
            "size":{
              "width":155,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4911426b00e04808a0b4262a353c729d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":1255,
                  "y":490},
                "size":{
                  "width":155,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u79.png"}},
{
          "id":"f1cd2315324a4301831dfbdf1d3060cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1080,
              "y":335},
            "size":{
              "width":175,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/流程说明_1/u41_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_2/u91_line.png"}},
{
          "id":"5bc2ec90c2b540d89b29bb9e05fc6384",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1142.5,
              "y":266},
            "size":{
              "width":25,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a26a3bf775fd4a0395f1640a427b2901",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1142.5,
                  "y":266},
                "size":{
                  "width":25,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_2/u92.png"}},
{
          "id":"b49435104b60469f8c9b11c191ad03bc",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":940,
              "y":295},
            "size":{
              "width":140,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae4050dd73364204932da9059fe56e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":940,
                  "y":295},
                "size":{
                  "width":140,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_2/u94.png"}},
{
          "id":"7a55cc93099f4b5b94f638e4690f650c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1004,
              "y":515},
            "size":{
              "width":251,
              "height":10},
            "rotation":"180",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/流程说明_1/u41_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_2/u96_line.png"}},
{
          "id":"5756e395dc1f491189e11ef0632ad9f0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1005,
              "y":385},
            "size":{
              "width":10,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_2/u97_line.png"}},
{
          "id":"e71072bfe8464cbc945f91ef26138b3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":964,
              "y":454.5},
            "size":{
              "width":92,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98d26931ac804a96b1a336845c8cbd84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":964,
                  "y":454.5},
                "size":{
                  "width":92,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_2/u98.png"}},
{
          "id":"4727257029c2477d87661c88c473257a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":1255,
              "y":650},
            "size":{
              "width":155,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b58f469566742e1b1357d2d84d665bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":1255,
                  "y":650},
                "size":{
                  "width":155,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u79.png"}},
{
          "id":"c2357efa654c4454b86204897ab40d81",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":550},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0db9405533fe463086abd1d19e80ba76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":550},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}]},
{
          "id":"883a7d67a3e94339a838d14c2a17939a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1332,
              "y":710},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1266d35e9cff487ba54208d15ddcb480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1332,
                  "y":710},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"813c264ad0004a50b614ea008df384fc",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1255,
              "y":850},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7852e838bb641bd90a45e5005ed25ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1255,
                  "y":850},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"c94243603d0f4657ac5b6bd36f931c2f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":1255},
            "size":{
              "width":980,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/流程说明_1/u41_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_2/u108_line.png"}},
{
          "id":"79372583829e4ce1a27fb4ade81410d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":1390},
            "size":{
              "width":465,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8f00125c7c04c56b5807d0799319386",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":1390},
                "size":{
                  "width":465,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"d9f4e737fcc04c0298a86ec14510cfbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":570,
              "y":1410},
            "size":{
              "width":400,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5c21ff6d17499a880f1a755877ed21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":570,
                  "y":1410},
                "size":{
                  "width":400,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb627e83787e4208840d6579fd283112",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1170,
              "y":1380},
            "size":{
              "width":360,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28acc4e8580b42cbaa388141141d55a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1170,
                  "y":1380},
                "size":{
                  "width":360,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"882a879491b5486eb0bcdf725c12d1f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1185,
              "y":1400},
            "size":{
              "width":335,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5413acd9fa04989b63c2dc296e1d9e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1185,
                  "y":1400},
                "size":{
                  "width":335,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dede7ba37bf14695be7d008e14cf3654",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":1360},
            "size":{
              "width":420,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"595673cc14f340b684386209f4e55852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":1360},
                "size":{
                  "width":420,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"ecc2105d7cf14b16a0a69a431d5a252c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":1384},
            "size":{
              "width":400,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d937466ffff6437cb8239800a468b1e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":1384},
                "size":{
                  "width":400,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"339c8480731e433aa37da80b0916c6d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":1450},
            "size":{
              "width":400,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2450b5cf4b784c57b3faa2a4d8d9660f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":1450},
                "size":{
                  "width":400,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8ba894d9578d4ba9a5e6e35911265376":{
      "scriptId":"u0"},
    "60a090f54c914812b46c8c788240b041":{
      "scriptId":"u1"},
    "3e132a17d028417bba038e075e5c92ff":{
      "scriptId":"u2"},
    "0293ea4ef30b4bed8a6008ea7348f3d5":{
      "scriptId":"u3"},
    "c69b8d93cc7f4ba38c01a647a20a9c79":{
      "scriptId":"u4"},
    "6fc0ac51d4fc4fd2aae3a03ac7743a41":{
      "scriptId":"u5"},
    "9ce283d815f94a2d8b1d7fb836fed607":{
      "scriptId":"u6"},
    "043f3eddd6c349089ef3473021b7b48e":{
      "scriptId":"u7"},
    "df8f7cb0196d4bdf9974811779ea1ae9":{
      "scriptId":"u8"},
    "2e1fbcade0384b8d8858e8992efe795e":{
      "scriptId":"u9"},
    "4a3188a7266243d496c735bef2073b46":{
      "scriptId":"u10"},
    "e7ee3bc4f8eb497abe2394e5705f371f":{
      "scriptId":"u11"},
    "3922b18476c4436fac92342bd9a3a22b":{
      "scriptId":"u12"},
    "5d596d63255a498e8dce4d5968241289":{
      "scriptId":"u13"},
    "45762b4a4b004acb9d2c2523d526743f":{
      "scriptId":"u14"},
    "768c0eb35ebb4b399351304b402901d8":{
      "scriptId":"u15"},
    "61e50636f8e14213abd933ac91c23187":{
      "scriptId":"u16"},
    "67643ac4e2cd4233b59ee64fb79d44ef":{
      "scriptId":"u17"},
    "3aa888711b5740d3b2a8ed608e925f63":{
      "scriptId":"u18"},
    "235527dfd02f43a38294889b47669156":{
      "scriptId":"u19"},
    "7cc07dff9a4e4908befab866f5fe13a3":{
      "scriptId":"u20"},
    "eb81489cd18146f5a20685d70ec877d4":{
      "scriptId":"u21"},
    "3410aeb6365346b0a18fcf7978cd739f":{
      "scriptId":"u22"},
    "08b797fc99014d4a8ac8072de0394044":{
      "scriptId":"u23"},
    "dafc9860bdaf4aa69861b42fab0b2394":{
      "scriptId":"u24"},
    "8989590e167b457ab2e1b40b492d081b":{
      "scriptId":"u25"},
    "a619b9e4c40b433eb89ce73cc47948c2":{
      "scriptId":"u26"},
    "654b536676384cdf81e5b6d21174b0f4":{
      "scriptId":"u27"},
    "d9c531a88ab5416d979cec25655b2ad8":{
      "scriptId":"u28"},
    "fb130d663b1e4f329574d2eb15ced1cc":{
      "scriptId":"u29"},
    "0fa5613ea73c4ab19c6ec20320af934d":{
      "scriptId":"u30"},
    "517f005d4206407cb3cbfdb5736ac076":{
      "scriptId":"u31"},
    "d8a8d536d8da4301b1e70836d97aaaa2":{
      "scriptId":"u32"},
    "2fe06d35e1ae433eb6c645c9f2e4e5f1":{
      "scriptId":"u33"},
    "d0ccf9dcd41c42b0b914cd88a63e42e0":{
      "scriptId":"u34"},
    "0fe1f128967a483abccf715d4e4515ba":{
      "scriptId":"u35"},
    "d99b128954de4d64853395bf27ce2a94":{
      "scriptId":"u36"},
    "7f645b23c64e481a9ba3847110d8b4cb":{
      "scriptId":"u37"},
    "a6491547a66149eba2283921e665ec60":{
      "scriptId":"u38"},
    "5aafb3362edd449d93d93356486ceb20":{
      "scriptId":"u39"},
    "1843091baa15421aa2a37438ba7679b8":{
      "scriptId":"u40"},
    "9887978bfdfc46c8a7dad8bfaa9e6510":{
      "scriptId":"u41"},
    "85e40bb7d3c14ec2b6b2c979daf0a626":{
      "scriptId":"u42"},
    "42bdfa40fa9d4db2b62b8d2585743152":{
      "scriptId":"u43"},
    "60a292dd443040b59ab0602ebfaf8927":{
      "scriptId":"u44"},
    "5b6d3acc16424338ba7b4e079763e1d8":{
      "scriptId":"u45"},
    "871040723cba4be89d028cf0f6469b16":{
      "scriptId":"u46"},
    "67c92c16648743fbbac84d9c098b821d":{
      "scriptId":"u47"},
    "f191dc1c48514ea58d3d1ed9b5e1247a":{
      "scriptId":"u48"},
    "fab7afe95624406584dedaf19be90964":{
      "scriptId":"u49"},
    "0df0e69b4ab348bbbf0339796be969a6":{
      "scriptId":"u50"},
    "a3f79bbf83d14f4bbc63c772ecaaa013":{
      "scriptId":"u51"},
    "fd301f75d50f4b1da41b2ab8b5ff7979":{
      "scriptId":"u52"},
    "5769aef921c744f6aabb7f559450592d":{
      "scriptId":"u53"},
    "45d9c7d4df054a3497a8686cdd1d39e7":{
      "scriptId":"u54"},
    "5385c971ebe14cd2b137942b9d82b97a":{
      "scriptId":"u55"},
    "b6da76fe633f4e4399ea41bb8560c032":{
      "scriptId":"u56"},
    "041e91f5b55c43dc9b559c1da564d41c":{
      "scriptId":"u57"},
    "f0efc689fde141d689dfceaf05be2df5":{
      "scriptId":"u58"},
    "0e6cb93cee194a48b9efbe26f80dc190":{
      "scriptId":"u59"},
    "4e951474794944a4b806da03ed1ff883":{
      "scriptId":"u60"},
    "4f57a03c6687451d8a4320817d06eb9e":{
      "scriptId":"u61"},
    "a5dc9847ecb444cdbcaaf3611c341bba":{
      "scriptId":"u62"},
    "318b4d9c4d504e19917c5738a3f3d34a":{
      "scriptId":"u63"},
    "f9ecf90f8a674d0b999c177ca91c4534":{
      "scriptId":"u64"},
    "5edf49cec7644e8390ce274bef0d5672":{
      "scriptId":"u65"},
    "f45c124907964dcc8c5cda78742c14a8":{
      "scriptId":"u66"},
    "f6280164ffdc4ee68174aedaa3924dbd":{
      "scriptId":"u67"},
    "29db337932ae425f890c43436ca378b2":{
      "scriptId":"u68"},
    "a329f66663b1450499ad9fafe3d7d80c":{
      "scriptId":"u69"},
    "e8e93e6553034dabb79a7794cd60dded":{
      "scriptId":"u70"},
    "c0ab3151e0cb42949bccc6d1407948c9":{
      "scriptId":"u71"},
    "e65b4f4a184344e8b7f5b65b8d7a6b1a":{
      "scriptId":"u72"},
    "f4985dd8c04241deb9fe658e128ec614":{
      "scriptId":"u73"},
    "93776499e1074fbe8f6ef44bc91b5fa1":{
      "scriptId":"u74"},
    "ea1cbaa108534b6d91ed04b4343bb385":{
      "scriptId":"u75"},
    "f928f03e4bec4943ad6669988de92055":{
      "scriptId":"u76"},
    "54af874ccef04d2da12a443d95898573":{
      "scriptId":"u77"},
    "fbe8c341e9644e98901b7065ee1d54a3":{
      "scriptId":"u78"},
    "375c7d32b27245b08af77d4267cd79f9":{
      "scriptId":"u79"},
    "6c64013ef4a4430ca07615b90d7f18b3":{
      "scriptId":"u80"},
    "8f6c0b2ab2be481bbc0271a7d26f48b7":{
      "scriptId":"u81"},
    "ccd56426ee6d4ad18491a0456aa6daf0":{
      "scriptId":"u82"},
    "cac499fd51144bcbbb761a2ce534eaea":{
      "scriptId":"u83"},
    "4d9a82234bca4a01931f7b76b77b0433":{
      "scriptId":"u84"},
    "f21708b244ba4bc29e6ba7497f8f8eb7":{
      "scriptId":"u85"},
    "a4cc2cde20c4468d8aa7f530731e0a22":{
      "scriptId":"u86"},
    "e2e9666f911d40ff8b757c8574418835":{
      "scriptId":"u87"},
    "6bd91206e56441e296b4fc15aef548ef":{
      "scriptId":"u88"},
    "2130f154af234a949fe3b0b6707b7fd5":{
      "scriptId":"u89"},
    "4911426b00e04808a0b4262a353c729d":{
      "scriptId":"u90"},
    "f1cd2315324a4301831dfbdf1d3060cf":{
      "scriptId":"u91"},
    "5bc2ec90c2b540d89b29bb9e05fc6384":{
      "scriptId":"u92"},
    "a26a3bf775fd4a0395f1640a427b2901":{
      "scriptId":"u93"},
    "b49435104b60469f8c9b11c191ad03bc":{
      "scriptId":"u94"},
    "ae4050dd73364204932da9059fe56e28":{
      "scriptId":"u95"},
    "7a55cc93099f4b5b94f638e4690f650c":{
      "scriptId":"u96"},
    "5756e395dc1f491189e11ef0632ad9f0":{
      "scriptId":"u97"},
    "e71072bfe8464cbc945f91ef26138b3e":{
      "scriptId":"u98"},
    "98d26931ac804a96b1a336845c8cbd84":{
      "scriptId":"u99"},
    "4727257029c2477d87661c88c473257a":{
      "scriptId":"u100"},
    "3b58f469566742e1b1357d2d84d665bb":{
      "scriptId":"u101"},
    "c2357efa654c4454b86204897ab40d81":{
      "scriptId":"u102"},
    "0db9405533fe463086abd1d19e80ba76":{
      "scriptId":"u103"},
    "883a7d67a3e94339a838d14c2a17939a":{
      "scriptId":"u104"},
    "1266d35e9cff487ba54208d15ddcb480":{
      "scriptId":"u105"},
    "813c264ad0004a50b614ea008df384fc":{
      "scriptId":"u106"},
    "b7852e838bb641bd90a45e5005ed25ae":{
      "scriptId":"u107"},
    "c94243603d0f4657ac5b6bd36f931c2f":{
      "scriptId":"u108"},
    "79372583829e4ce1a27fb4ade81410d7":{
      "scriptId":"u109"},
    "d8f00125c7c04c56b5807d0799319386":{
      "scriptId":"u110"},
    "d9f4e737fcc04c0298a86ec14510cfbd":{
      "scriptId":"u111"},
    "fe5c21ff6d17499a880f1a755877ed21":{
      "scriptId":"u112"},
    "eb627e83787e4208840d6579fd283112":{
      "scriptId":"u113"},
    "28acc4e8580b42cbaa388141141d55a0":{
      "scriptId":"u114"},
    "882a879491b5486eb0bcdf725c12d1f5":{
      "scriptId":"u115"},
    "b5413acd9fa04989b63c2dc296e1d9e9":{
      "scriptId":"u116"},
    "dede7ba37bf14695be7d008e14cf3654":{
      "scriptId":"u117"},
    "595673cc14f340b684386209f4e55852":{
      "scriptId":"u118"},
    "ecc2105d7cf14b16a0a69a431d5a252c":{
      "scriptId":"u119"},
    "d937466ffff6437cb8239800a468b1e7":{
      "scriptId":"u120"},
    "339c8480731e433aa37da80b0916c6d2":{
      "scriptId":"u121"},
    "2450b5cf4b784c57b3faa2a4d8d9660f":{
      "scriptId":"u122"}}});