$axure.loadCurrentPage({
  "url":"采购方发布采购单.html",
  "generationDate":new Date(1462500150533.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ddd734c64d6d4b76ad5caa0eae2c125e",
    "type":"Axure:Page",
    "name":"采购方发布采购单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"95732459cbfa457ea57513864df8189b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":94},
            "size":{
              "width":1045,
              "height":1736},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b18e817125646f6a7f86ba63e32da57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":94},
                "size":{
                  "width":1045,
                  "height":1736},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u0.png"}},
{
          "id":"e6c7eedb7af641b1a255ea7ebad54f08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":480,
              "y":112},
            "size":{
              "width":170,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73cb6bbc595f4525a40e7c6a6b544009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":480,
                  "y":112},
                "size":{
                  "width":170,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e13fb388dd54944ac5f6011070e02f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":150},
            "size":{
              "width":1045,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f415f4058d54902a99be2e5934ba67e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":150},
                "size":{
                  "width":1045,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u4.png"}},
{
          "id":"deb95c53c53940af999d814ec9515abd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":166},
            "size":{
              "width":66,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee9cd76672314232801411f82972367f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":166},
                "size":{
                  "width":66,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ad3321fbaf448b1b0cdbc0c62d72efd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":200},
            "size":{
              "width":1045,
              "height":56},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f528f3936d474c599539e94eadcd3f06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":200},
                "size":{
                  "width":1045,
                  "height":56},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u8.png"}},
{
          "id":"5d3439dab6fc47e2bbc017f328c75fd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":218},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fee210467f8f41edb91c782979274f22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":218},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0b870af42234589aa448056774ff362",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "hint":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}}},
            "location":{
              "x":146,
              "y":215},
            "size":{
              "width":684,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"采购单标题(必填)，可填写采购商品名称或者关键字，不能超过30个字。"},
{
          "id":"d5e001c87f4f45889bceb9b8aa2f7b7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":256},
            "size":{
              "width":1045,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5be1b80aa46d4aa1b6de4875c84ae382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":256},
                "size":{
                  "width":1045,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u4.png"}},
{
          "id":"6741d103063e43daa10e6eff29ec0b24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":272},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dbc9d3a091b41b2b21c6f76ba3aa639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":272},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e33e9d835ff436cae4bd5075bc071e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":306},
            "size":{
              "width":1045,
              "height":234},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac5c1cb6c7a14056a696db49f74f7f14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":306},
                "size":{
                  "width":1045,
                  "height":234},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u17.png"}},
{
          "id":"4e12bbbd57ef47c884ae077de637c8b4",
          "label":"现货",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":84,
              "y":324},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a697f9e0d9fb426a88343c556652169c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":84,
                  "y":324},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"51c93ec17bcd4ebba0a8622c0fb91614",
          "label":"加工/定制",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":234,
              "y":324},
            "size":{
              "width":126,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43df459f1c60468c83fe9052a44cc393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":234,
                  "y":324},
                "size":{
                  "width":126,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"e55a1e4aeaba40e89a727ae58ca841e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":84,
              "y":360},
            "size":{
              "width":1016,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad30b5dda8274d1493f0ba34be8253dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":84,
                  "y":360},
                "size":{
                  "width":1016,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u23.png"}},
{
          "id":"027bb4820c9345c9ae07dce4cfa643af",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":102,
              "y":376},
            "size":{
              "width":108,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bef6e7a75310445b8fde1316243a3016",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":102,
                  "y":376},
                "size":{
                  "width":108,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c3d5c1925d848da9dec89a67f2c8c49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":250,
              "y":376},
            "size":{
              "width":108,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a9f21617d74160b10e26ab769350b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":250,
                  "y":376},
                "size":{
                  "width":108,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3548fc0318d408b884a4309c254537c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":397,
              "y":376},
            "size":{
              "width":108,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"794cf8ea27f94615bb1c50fee7ba8fbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":397,
                  "y":376},
                "size":{
                  "width":108,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1899cc61973d4beaabcd6e476a04d75b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":545,
              "y":376},
            "size":{
              "width":108,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdda3d9519b24e35aba0577504adc744",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":545,
                  "y":376},
                "size":{
                  "width":108,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42e15ad5c7d44df089d17aeb3e3fedc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":693,
              "y":376},
            "size":{
              "width":108,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8c68e71721544c784a65b1c6e96ec05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":693,
                  "y":376},
                "size":{
                  "width":108,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce2a7df851404bfc9ac4a6917301afd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":840,
              "y":376},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfca28a94cab4450bac480438a89fbe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":840,
                  "y":376},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfe34340b7194a6497be3024956ae816",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":410},
            "size":{
              "width":1016,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d14f8347324a98a4bc90b721541f06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":410},
                "size":{
                  "width":1016,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u37.png"}},
{
          "id":"1ae4e8e1f27442028b246300d5974dd1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":422},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"229b5134e2864500924aef37e4b6df1b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":422},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fda2d8b3663f46a5a23bbdb8e92e5ef9",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":422},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2e8642713e1842f7a188deafcaeb72ae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":559,
              "y":422},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7b5c9cb774e04fc0912ce56238f2177d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":422},
            "size":{
              "width":120,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4d52cdb9aced43218ffd7baf0ebd3084",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":865,
              "y":422},
            "size":{
              "width":80,
              "height":25},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3def5cb09bba4f7eb453027dc33c7397",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":865,
                  "y":422},
                "size":{
                  "width":80,
                  "height":25},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u44.png"}},
{
          "id":"ded94391a61644089bfd27eb2be372fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":84,
              "y":470},
            "size":{
              "width":110,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c343a84d83945e4af12d7cc5de0c323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":84,
                  "y":470},
                "size":{
                  "width":110,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u46.png"}},
{
          "id":"494a068d724c4c5898228b128068a17d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":540},
            "size":{
              "width":1045,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddff66af314b474f97eee28c947d1f56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":540},
                "size":{
                  "width":1045,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u4.png"}},
{
          "id":"54d4e29b492149d0ba94a3e5c347bbe7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":556},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4686ce7b880c47f7879cf959bb995225",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":556},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"582f3608f41947caa9621b66238cbd50",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":590},
            "size":{
              "width":1045,
              "height":730},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a514e53b23154a26a3bf2f7aafa18250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":590},
                "size":{
                  "width":1045,
                  "height":730},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u52.png"}},
{
          "id":"38537b365a6648239cd27434277bf343",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":1320},
            "size":{
              "width":1045,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d278de1051824e18a35d909d962a1ba5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":1320},
                "size":{
                  "width":1045,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u4.png"}},
{
          "id":"9e761aa77372422da15f81734f3774f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":1336},
            "size":{
              "width":180,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25b09f08da1a42a983696326dd33f7e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":1336},
                "size":{
                  "width":180,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"009763f72f194fb6b4e35d1206c234d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":1370},
            "size":{
              "width":1045,
              "height":340},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee0b90db8f1452ab227f0bcbb078bf0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":1370},
                "size":{
                  "width":1045,
                  "height":340},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u58.png"}},
{
          "id":"2d15823ebdbe46c1b6746493eb70a95e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":1390},
            "size":{
              "width":676,
              "height":273}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f583b73d331f4a95b6f64cae20092a7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":1390},
                "size":{
                  "width":676,
                  "height":273}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u60.png"}},
{
          "id":"a03bbd28e31f419ea7551153e6552a3a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":350,
              "y":1750},
            "size":{
              "width":110,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af871e03cd2845d999af4e1a49b1b34a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":350,
                  "y":1750},
                "size":{
                  "width":110,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u62.png"}},
{
          "id":"055391b890b7454b805b3e84136a8434",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":640,
              "y":1750},
            "size":{
              "width":110,
              "height":40},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78162126aa64439181001641677b6ad3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":640,
                  "y":1750},
                "size":{
                  "width":110,
                  "height":40},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u62.png"}},
{
          "id":"54210facc5ac44b686e9bd6c9122c8c3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":600},
            "size":{
              "width":932,
              "height":697}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb8bcea5309f4885bd77c0531d341bf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":600},
                "size":{
                  "width":932,
                  "height":697}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u66.png"}},
{
          "id":"f8e4bd69372341aba16a246c6574227a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1030,
              "y":419},
            "size":{
              "width":29,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53630a92243f4c729d92617c3529b65b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1030,
                  "y":419},
                "size":{
                  "width":29,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/采购方发布采购单/u68.png"}},
{
          "id":"10cd43b1d13e4bcc9d4983839da98de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":1000,
              "y":376},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa5fd817b8674ef79ac65083474aa708",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":1000,
                  "y":376},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef98f28428e144e1b397e69ef4ec8533",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":1360,
              "height":10},
            "borderWidth":"3",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购方发布采购单/u72_line.png"}},
{
          "id":"c776022724c34b368dfe597f3763ce5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":400,
              "y":30},
            "size":{
              "width":430,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472cb1d153db45f1a003953c2035c4b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":400,
                  "y":30},
                "size":{
                  "width":430,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "95732459cbfa457ea57513864df8189b":{
      "scriptId":"u0"},
    "6b18e817125646f6a7f86ba63e32da57":{
      "scriptId":"u1"},
    "e6c7eedb7af641b1a255ea7ebad54f08":{
      "scriptId":"u2"},
    "73cb6bbc595f4525a40e7c6a6b544009":{
      "scriptId":"u3"},
    "2e13fb388dd54944ac5f6011070e02f6":{
      "scriptId":"u4"},
    "4f415f4058d54902a99be2e5934ba67e":{
      "scriptId":"u5"},
    "deb95c53c53940af999d814ec9515abd":{
      "scriptId":"u6"},
    "ee9cd76672314232801411f82972367f":{
      "scriptId":"u7"},
    "3ad3321fbaf448b1b0cdbc0c62d72efd":{
      "scriptId":"u8"},
    "f528f3936d474c599539e94eadcd3f06":{
      "scriptId":"u9"},
    "5d3439dab6fc47e2bbc017f328c75fd2":{
      "scriptId":"u10"},
    "fee210467f8f41edb91c782979274f22":{
      "scriptId":"u11"},
    "e0b870af42234589aa448056774ff362":{
      "scriptId":"u12"},
    "d5e001c87f4f45889bceb9b8aa2f7b7e":{
      "scriptId":"u13"},
    "5be1b80aa46d4aa1b6de4875c84ae382":{
      "scriptId":"u14"},
    "6741d103063e43daa10e6eff29ec0b24":{
      "scriptId":"u15"},
    "8dbc9d3a091b41b2b21c6f76ba3aa639":{
      "scriptId":"u16"},
    "7e33e9d835ff436cae4bd5075bc071e2":{
      "scriptId":"u17"},
    "ac5c1cb6c7a14056a696db49f74f7f14":{
      "scriptId":"u18"},
    "4e12bbbd57ef47c884ae077de637c8b4":{
      "scriptId":"u19"},
    "a697f9e0d9fb426a88343c556652169c":{
      "scriptId":"u20"},
    "51c93ec17bcd4ebba0a8622c0fb91614":{
      "scriptId":"u21"},
    "43df459f1c60468c83fe9052a44cc393":{
      "scriptId":"u22"},
    "e55a1e4aeaba40e89a727ae58ca841e5":{
      "scriptId":"u23"},
    "ad30b5dda8274d1493f0ba34be8253dc":{
      "scriptId":"u24"},
    "027bb4820c9345c9ae07dce4cfa643af":{
      "scriptId":"u25"},
    "bef6e7a75310445b8fde1316243a3016":{
      "scriptId":"u26"},
    "0c3d5c1925d848da9dec89a67f2c8c49":{
      "scriptId":"u27"},
    "84a9f21617d74160b10e26ab769350b2":{
      "scriptId":"u28"},
    "c3548fc0318d408b884a4309c254537c":{
      "scriptId":"u29"},
    "794cf8ea27f94615bb1c50fee7ba8fbe":{
      "scriptId":"u30"},
    "1899cc61973d4beaabcd6e476a04d75b":{
      "scriptId":"u31"},
    "fdda3d9519b24e35aba0577504adc744":{
      "scriptId":"u32"},
    "42e15ad5c7d44df089d17aeb3e3fedc8":{
      "scriptId":"u33"},
    "a8c68e71721544c784a65b1c6e96ec05":{
      "scriptId":"u34"},
    "ce2a7df851404bfc9ac4a6917301afd2":{
      "scriptId":"u35"},
    "bfca28a94cab4450bac480438a89fbe3":{
      "scriptId":"u36"},
    "dfe34340b7194a6497be3024956ae816":{
      "scriptId":"u37"},
    "b9d14f8347324a98a4bc90b721541f06":{
      "scriptId":"u38"},
    "1ae4e8e1f27442028b246300d5974dd1":{
      "scriptId":"u39"},
    "229b5134e2864500924aef37e4b6df1b":{
      "scriptId":"u40"},
    "fda2d8b3663f46a5a23bbdb8e92e5ef9":{
      "scriptId":"u41"},
    "2e8642713e1842f7a188deafcaeb72ae":{
      "scriptId":"u42"},
    "7b5c9cb774e04fc0912ce56238f2177d":{
      "scriptId":"u43"},
    "4d52cdb9aced43218ffd7baf0ebd3084":{
      "scriptId":"u44"},
    "3def5cb09bba4f7eb453027dc33c7397":{
      "scriptId":"u45"},
    "ded94391a61644089bfd27eb2be372fe":{
      "scriptId":"u46"},
    "8c343a84d83945e4af12d7cc5de0c323":{
      "scriptId":"u47"},
    "494a068d724c4c5898228b128068a17d":{
      "scriptId":"u48"},
    "ddff66af314b474f97eee28c947d1f56":{
      "scriptId":"u49"},
    "54d4e29b492149d0ba94a3e5c347bbe7":{
      "scriptId":"u50"},
    "4686ce7b880c47f7879cf959bb995225":{
      "scriptId":"u51"},
    "582f3608f41947caa9621b66238cbd50":{
      "scriptId":"u52"},
    "a514e53b23154a26a3bf2f7aafa18250":{
      "scriptId":"u53"},
    "38537b365a6648239cd27434277bf343":{
      "scriptId":"u54"},
    "d278de1051824e18a35d909d962a1ba5":{
      "scriptId":"u55"},
    "9e761aa77372422da15f81734f3774f7":{
      "scriptId":"u56"},
    "25b09f08da1a42a983696326dd33f7e1":{
      "scriptId":"u57"},
    "009763f72f194fb6b4e35d1206c234d8":{
      "scriptId":"u58"},
    "8ee0b90db8f1452ab227f0bcbb078bf0":{
      "scriptId":"u59"},
    "2d15823ebdbe46c1b6746493eb70a95e":{
      "scriptId":"u60"},
    "f583b73d331f4a95b6f64cae20092a7f":{
      "scriptId":"u61"},
    "a03bbd28e31f419ea7551153e6552a3a":{
      "scriptId":"u62"},
    "af871e03cd2845d999af4e1a49b1b34a":{
      "scriptId":"u63"},
    "055391b890b7454b805b3e84136a8434":{
      "scriptId":"u64"},
    "78162126aa64439181001641677b6ad3":{
      "scriptId":"u65"},
    "54210facc5ac44b686e9bd6c9122c8c3":{
      "scriptId":"u66"},
    "fb8bcea5309f4885bd77c0531d341bf7":{
      "scriptId":"u67"},
    "f8e4bd69372341aba16a246c6574227a":{
      "scriptId":"u68"},
    "53630a92243f4c729d92617c3529b65b":{
      "scriptId":"u69"},
    "10cd43b1d13e4bcc9d4983839da98de6":{
      "scriptId":"u70"},
    "fa5fd817b8674ef79ac65083474aa708":{
      "scriptId":"u71"},
    "ef98f28428e144e1b397e69ef4ec8533":{
      "scriptId":"u72"},
    "c776022724c34b368dfe597f3763ce5d":{
      "scriptId":"u73"},
    "472cb1d153db45f1a003953c2035c4b0":{
      "scriptId":"u74"}}});