$axure.loadCurrentPage({
  "url":"报价对比.html",
  "generationDate":new Date(1462500151912.67),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5a69cc2803b94fc9819e450a8ee75afa",
    "type":"Axure:Page",
    "name":"报价对比",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3ff8d59c690c4c8aa8bb0473e51d65e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":205},
            "size":{
              "width":1056,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6de66e933fbb497c96329acdddfce179",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":205},
                "size":{
                  "width":1056,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报价对比/u0.png"}},
{
          "id":"6ade042e9618421cbf93292b07f3ffd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":520,
              "y":222},
            "size":{
              "width":230,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5da05bef30de4924bcd85a19926021aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":520,
                  "y":222},
                "size":{
                  "width":230,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d2a0458248cb4c98bb9a209145da7296",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":150,
              "y":301},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a731ef598a2423f911ee07ff3946398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":150,
                  "y":301},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"49244ea3f5c341b69068ef88a41440fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":220,
              "y":301},
            "size":{
              "width":210,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b84879fce2452192c3d0435827a032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":220,
                  "y":301},
                "size":{
                  "width":210,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b8b863693db457fb6a034bf3119ecd4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":350},
            "size":{
              "width":1050,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a17b8ed3b2042a588a2a00462ef5f54",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "size":{
                  "width":155,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fab7b795b91946eb898addd9f84f460a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "size":{
                      "width":155,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u9.png"}},
{
              "id":"7040b9cab4ca41538ab623eeb3d19019",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":50},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a6fcd600c064f0a9cfc773fd6f207a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":50},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u19.png"}},
{
              "id":"84464931f7eb4e63bd60c320084b8faf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":95},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90acb5e50bdd4dfabfe031ba63ba239e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":95},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u19.png"}},
{
              "id":"8cf64c37667443a3a79fa336c0b16041",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":155,
                  "y":0},
                "size":{
                  "width":224,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5d40551257ca424f84bb9ba9156889e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "location":{
                      "x":155,
                      "y":0},
                    "size":{
                      "width":224,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u11.png"}},
{
              "id":"350de0904d3e44a29e626438557e6679",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":50},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b2436120cd434b57bcd58d2611ad08ca",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":50},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"a6954e8d963c42d485b67db9c64c91f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":95},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cc6c8568afbf46d79a8072dfd48cb572",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":95},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"b385b99cf1ad4d038e729682b2896f5f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":379,
                  "y":0},
                "size":{
                  "width":224,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce5073737bfd4a64933b42a28e40655b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "location":{
                      "x":379,
                      "y":0},
                    "size":{
                      "width":224,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u11.png"}},
{
              "id":"7f49c0c5b0a44c53b266bf837b9512a7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":50},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e5de8fa0ebb4e15bef23a8018b62c96",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":50},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"17958cfd87e5494b809b4d60e7c0e30a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":95},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"deb9cf9c9d914649b7563e9aee805dc0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":95},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"5704c4fdbf804c8698b2d654cc0c2b12",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":603,
                  "y":0},
                "size":{
                  "width":224,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e000dc6667c4ff49461ad734b9ac617",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "location":{
                      "x":603,
                      "y":0},
                    "size":{
                      "width":224,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u11.png"}},
{
              "id":"7623e87990674a49a4eab8a2c754f838",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":50},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54f1e8bf3d9040dfa2d0145c51b8d985",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":50},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"a97c5a95895a4e42addfcf786e064a94",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":95},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7939f750ac474a64a98ef00fee55bf2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":95},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"62190ae6490941aa8676247d9eaefd16",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7},
                "location":{
                  "x":827,
                  "y":0},
                "size":{
                  "width":223,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"95ef1d7154134f328e5ae798ccd80316",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7},
                    "location":{
                      "x":827,
                      "y":0},
                    "size":{
                      "width":223,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u17.png"}},
{
              "id":"bdfe8e284bb440de83645dc92a3aa734",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":50},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b52ff601430649409a4d5a4d43cafed5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":50},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u27.png"}},
{
              "id":"448bff9ed18b4d5eaedb6c79bc66fde1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":95},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fec42802543b4e16b638ddd355c4bc3c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":95},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u27.png"}},
{
              "id":"e548cc9d54a345f3ae0e6a2810a3dec0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":140},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b11a4aa7161940ffb0c5382872b4eac8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":140},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u19.png"}},
{
              "id":"9aeb23086c2543eaa5cfa8fe0b5699af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":140},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"feca661d256c4289a0e359becd43749c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":140},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"e29bab7a8bd04db2a332ae56e41e4224",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":140},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"362553dc71e9486c8f4e1dcd0cd547d3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":140},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"bbb5c6f71fb84eba9eca383e1de20abc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":140},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"51b581b2ae1e46538016b14895e9ded0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":140},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"ab6bcff154384d34a3f112dfbf5bfcdf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":140},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3193cac640794fcfa5bd0b65dd2b13a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":140},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u27.png"}},
{
              "id":"4c53d25b8a3f41418ef74e4939ea06ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":185},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89df92335b334951b20c9a8c3c5e163d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":185},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u19.png"}},
{
              "id":"1645bca8c5684b778d5c09ca9a9411ab",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":185},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c572560e11564ba9a431b88c58a7f024",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":185},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"2f242912ae0f41b78e279e601d6bcbb2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":185},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"07adab9caa7b4ddbbee0a0c1c179c7b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":185},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"ca175fe1f39c485a8a6db6feb263d813",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":185},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d6c249019fee44349bae3530159c00b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":185},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"665e45cffe5543f081fb0aaacb93e9cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":185},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b28b23842484412cb3d90ee2ff8277a6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":185},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u27.png"}},
{
              "id":"05f42556e87a47abb0ecb541c17143f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":230},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5179330054354902ba069b2b3075e7cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":230},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u19.png"}},
{
              "id":"adc6c6f823b94c629b781e9dad3f0e55",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":230},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00c349e1904348d591b117c0d266db32",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":230},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"d81702d29f7a43f59692be2c579ad18e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":230},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"512862565c824ce4abd3d0460bc5df31",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":230},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"e1cf5f024490410e93584db58b1b53b2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":230},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7523e61e49e44fbac0d00482e9dd162",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":230},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"1bc404d50430402bb41b679b9c5a3d6f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":230},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7762c2d2c3644b5caf473592f5a02f54",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":230},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u27.png"}},
{
              "id":"cfec86ac1458406a9b0919b16d6811f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":275},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"973e034ec6a346ac9dcc99587d1ef785",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":275},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u19.png"}},
{
              "id":"3d388599c745480db0fde4470266a321",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":275},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16b6ebd00e03411aa5f5fda4e629df2a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":275},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"b8a96b8b7bb74e1fb4f4bb6d8f5cfd49",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":275},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d55102c9cc642ffa9e05362a2dcfc5d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":275},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"e15730dc7abf425c8b0af26fb02c8224",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":275},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"679516ea814047fa98bb6d82e2ffe0c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":275},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"880d36c0c8824e99aa497fdae8ce8f4d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":275},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb3e61c0c7754460bbedbcaa5cd964d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":275},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u27.png"}},
{
              "id":"0b278da5ff18484284cfe4fb76d41d02",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":365},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a923138264d47f39bb4961055a7492a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":365},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u89.png"}},
{
              "id":"93627911f943431495b13cbed7d9ee74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":365},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ddeabc13eca54ddd882529db36666302",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":365},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u91.png"}},
{
              "id":"c3fd7507700f4e02a3f28d62d685f2e3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":365},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d0f69605a45548608cd0223d968e784c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":365},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u91.png"}},
{
              "id":"927aba110ee64548857752c8b621418d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":365},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ee1f559e7c404e4eb3aea74e49b8059f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":365},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u91.png"}},
{
              "id":"a8990c4142934a11a9d3a4e0c32e5f8d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":365},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"535fd594fcb44df086adda4879e4f643",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":365},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u97.png"}},
{
              "id":"b039876df0af466d93bdbd919eae6cd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":155,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f9d7b5b5b1c4fd382b7db68f7454d8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":155,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u19.png"}},
{
              "id":"401146afcd434a7991304f970e1757e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":320},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7623d3d12d6e4ea4a6a4c831b40f48bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":320},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"81d66387a14a4f54b9abd8d0f28664a9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":320},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f3fa040e39114442a2acfce645fca54e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":379,
                      "y":320},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"d53cef7a72324ac98f422def03e27756",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":603,
                  "y":320},
                "size":{
                  "width":224,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fff613070db6447486b7b3e04f0c1792",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":603,
                      "y":320},
                    "size":{
                      "width":224,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u21.png"}},
{
              "id":"18458a0b86f14a5eb22ad4f56986eb3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":827,
                  "y":320},
                "size":{
                  "width":223,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6d3fa2fc7280445db211c21fb3f899fa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":827,
                      "y":320},
                    "size":{
                      "width":223,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/报价对比/u27.png"}}]},
{
          "id":"717f016c531748b18f67345acf433a67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1050,
              "y":301},
            "size":{
              "width":150,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00b95cc25e2b408e979726c0f43d7c7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1050,
                  "y":301},
                "size":{
                  "width":150,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3820f3bdcae4168ae6f0a129667ba0f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2,
              "y":140},
            "size":{
              "width":1340,
              "height":10},
            "borderWidth":"3",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购商查看报价表/u248_line.png"}},
{
          "id":"d9efb8aac6f1427d9d99871d2481a486",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":382,
              "y":56},
            "size":{
              "width":580,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04cc02ecd3274469ac4153a81fa8acc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":382,
                  "y":56},
                "size":{
                  "width":580,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3ff8d59c690c4c8aa8bb0473e51d65e2":{
      "scriptId":"u0"},
    "6de66e933fbb497c96329acdddfce179":{
      "scriptId":"u1"},
    "6ade042e9618421cbf93292b07f3ffd6":{
      "scriptId":"u2"},
    "5da05bef30de4924bcd85a19926021aa":{
      "scriptId":"u3"},
    "d2a0458248cb4c98bb9a209145da7296":{
      "scriptId":"u4"},
    "5a731ef598a2423f911ee07ff3946398":{
      "scriptId":"u5"},
    "49244ea3f5c341b69068ef88a41440fa":{
      "scriptId":"u6"},
    "71b84879fce2452192c3d0435827a032":{
      "scriptId":"u7"},
    "6b8b863693db457fb6a034bf3119ecd4":{
      "scriptId":"u8"},
    "0a17b8ed3b2042a588a2a00462ef5f54":{
      "scriptId":"u9"},
    "fab7b795b91946eb898addd9f84f460a":{
      "scriptId":"u10"},
    "8cf64c37667443a3a79fa336c0b16041":{
      "scriptId":"u11"},
    "5d40551257ca424f84bb9ba9156889e3":{
      "scriptId":"u12"},
    "b385b99cf1ad4d038e729682b2896f5f":{
      "scriptId":"u13"},
    "ce5073737bfd4a64933b42a28e40655b":{
      "scriptId":"u14"},
    "5704c4fdbf804c8698b2d654cc0c2b12":{
      "scriptId":"u15"},
    "4e000dc6667c4ff49461ad734b9ac617":{
      "scriptId":"u16"},
    "62190ae6490941aa8676247d9eaefd16":{
      "scriptId":"u17"},
    "95ef1d7154134f328e5ae798ccd80316":{
      "scriptId":"u18"},
    "7040b9cab4ca41538ab623eeb3d19019":{
      "scriptId":"u19"},
    "2a6fcd600c064f0a9cfc773fd6f207a6":{
      "scriptId":"u20"},
    "350de0904d3e44a29e626438557e6679":{
      "scriptId":"u21"},
    "b2436120cd434b57bcd58d2611ad08ca":{
      "scriptId":"u22"},
    "7f49c0c5b0a44c53b266bf837b9512a7":{
      "scriptId":"u23"},
    "8e5de8fa0ebb4e15bef23a8018b62c96":{
      "scriptId":"u24"},
    "7623e87990674a49a4eab8a2c754f838":{
      "scriptId":"u25"},
    "54f1e8bf3d9040dfa2d0145c51b8d985":{
      "scriptId":"u26"},
    "bdfe8e284bb440de83645dc92a3aa734":{
      "scriptId":"u27"},
    "b52ff601430649409a4d5a4d43cafed5":{
      "scriptId":"u28"},
    "84464931f7eb4e63bd60c320084b8faf":{
      "scriptId":"u29"},
    "90acb5e50bdd4dfabfe031ba63ba239e":{
      "scriptId":"u30"},
    "a6954e8d963c42d485b67db9c64c91f4":{
      "scriptId":"u31"},
    "cc6c8568afbf46d79a8072dfd48cb572":{
      "scriptId":"u32"},
    "17958cfd87e5494b809b4d60e7c0e30a":{
      "scriptId":"u33"},
    "deb9cf9c9d914649b7563e9aee805dc0":{
      "scriptId":"u34"},
    "a97c5a95895a4e42addfcf786e064a94":{
      "scriptId":"u35"},
    "7939f750ac474a64a98ef00fee55bf2d":{
      "scriptId":"u36"},
    "448bff9ed18b4d5eaedb6c79bc66fde1":{
      "scriptId":"u37"},
    "fec42802543b4e16b638ddd355c4bc3c":{
      "scriptId":"u38"},
    "e548cc9d54a345f3ae0e6a2810a3dec0":{
      "scriptId":"u39"},
    "b11a4aa7161940ffb0c5382872b4eac8":{
      "scriptId":"u40"},
    "9aeb23086c2543eaa5cfa8fe0b5699af":{
      "scriptId":"u41"},
    "feca661d256c4289a0e359becd43749c":{
      "scriptId":"u42"},
    "e29bab7a8bd04db2a332ae56e41e4224":{
      "scriptId":"u43"},
    "362553dc71e9486c8f4e1dcd0cd547d3":{
      "scriptId":"u44"},
    "bbb5c6f71fb84eba9eca383e1de20abc":{
      "scriptId":"u45"},
    "51b581b2ae1e46538016b14895e9ded0":{
      "scriptId":"u46"},
    "ab6bcff154384d34a3f112dfbf5bfcdf":{
      "scriptId":"u47"},
    "3193cac640794fcfa5bd0b65dd2b13a8":{
      "scriptId":"u48"},
    "4c53d25b8a3f41418ef74e4939ea06ae":{
      "scriptId":"u49"},
    "89df92335b334951b20c9a8c3c5e163d":{
      "scriptId":"u50"},
    "1645bca8c5684b778d5c09ca9a9411ab":{
      "scriptId":"u51"},
    "c572560e11564ba9a431b88c58a7f024":{
      "scriptId":"u52"},
    "2f242912ae0f41b78e279e601d6bcbb2":{
      "scriptId":"u53"},
    "07adab9caa7b4ddbbee0a0c1c179c7b2":{
      "scriptId":"u54"},
    "ca175fe1f39c485a8a6db6feb263d813":{
      "scriptId":"u55"},
    "d6c249019fee44349bae3530159c00b7":{
      "scriptId":"u56"},
    "665e45cffe5543f081fb0aaacb93e9cc":{
      "scriptId":"u57"},
    "b28b23842484412cb3d90ee2ff8277a6":{
      "scriptId":"u58"},
    "05f42556e87a47abb0ecb541c17143f9":{
      "scriptId":"u59"},
    "5179330054354902ba069b2b3075e7cc":{
      "scriptId":"u60"},
    "adc6c6f823b94c629b781e9dad3f0e55":{
      "scriptId":"u61"},
    "00c349e1904348d591b117c0d266db32":{
      "scriptId":"u62"},
    "d81702d29f7a43f59692be2c579ad18e":{
      "scriptId":"u63"},
    "512862565c824ce4abd3d0460bc5df31":{
      "scriptId":"u64"},
    "e1cf5f024490410e93584db58b1b53b2":{
      "scriptId":"u65"},
    "b7523e61e49e44fbac0d00482e9dd162":{
      "scriptId":"u66"},
    "1bc404d50430402bb41b679b9c5a3d6f":{
      "scriptId":"u67"},
    "7762c2d2c3644b5caf473592f5a02f54":{
      "scriptId":"u68"},
    "cfec86ac1458406a9b0919b16d6811f0":{
      "scriptId":"u69"},
    "973e034ec6a346ac9dcc99587d1ef785":{
      "scriptId":"u70"},
    "3d388599c745480db0fde4470266a321":{
      "scriptId":"u71"},
    "16b6ebd00e03411aa5f5fda4e629df2a":{
      "scriptId":"u72"},
    "b8a96b8b7bb74e1fb4f4bb6d8f5cfd49":{
      "scriptId":"u73"},
    "7d55102c9cc642ffa9e05362a2dcfc5d":{
      "scriptId":"u74"},
    "e15730dc7abf425c8b0af26fb02c8224":{
      "scriptId":"u75"},
    "679516ea814047fa98bb6d82e2ffe0c1":{
      "scriptId":"u76"},
    "880d36c0c8824e99aa497fdae8ce8f4d":{
      "scriptId":"u77"},
    "fb3e61c0c7754460bbedbcaa5cd964d2":{
      "scriptId":"u78"},
    "b039876df0af466d93bdbd919eae6cd4":{
      "scriptId":"u79"},
    "8f9d7b5b5b1c4fd382b7db68f7454d8f":{
      "scriptId":"u80"},
    "401146afcd434a7991304f970e1757e2":{
      "scriptId":"u81"},
    "7623d3d12d6e4ea4a6a4c831b40f48bd":{
      "scriptId":"u82"},
    "81d66387a14a4f54b9abd8d0f28664a9":{
      "scriptId":"u83"},
    "f3fa040e39114442a2acfce645fca54e":{
      "scriptId":"u84"},
    "d53cef7a72324ac98f422def03e27756":{
      "scriptId":"u85"},
    "fff613070db6447486b7b3e04f0c1792":{
      "scriptId":"u86"},
    "18458a0b86f14a5eb22ad4f56986eb3b":{
      "scriptId":"u87"},
    "6d3fa2fc7280445db211c21fb3f899fa":{
      "scriptId":"u88"},
    "0b278da5ff18484284cfe4fb76d41d02":{
      "scriptId":"u89"},
    "5a923138264d47f39bb4961055a7492a":{
      "scriptId":"u90"},
    "93627911f943431495b13cbed7d9ee74":{
      "scriptId":"u91"},
    "ddeabc13eca54ddd882529db36666302":{
      "scriptId":"u92"},
    "c3fd7507700f4e02a3f28d62d685f2e3":{
      "scriptId":"u93"},
    "d0f69605a45548608cd0223d968e784c":{
      "scriptId":"u94"},
    "927aba110ee64548857752c8b621418d":{
      "scriptId":"u95"},
    "ee1f559e7c404e4eb3aea74e49b8059f":{
      "scriptId":"u96"},
    "a8990c4142934a11a9d3a4e0c32e5f8d":{
      "scriptId":"u97"},
    "535fd594fcb44df086adda4879e4f643":{
      "scriptId":"u98"},
    "717f016c531748b18f67345acf433a67":{
      "scriptId":"u99"},
    "00b95cc25e2b408e979726c0f43d7c7f":{
      "scriptId":"u100"},
    "b3820f3bdcae4168ae6f0a129667ba0f":{
      "scriptId":"u101"},
    "d9efb8aac6f1427d9d99871d2481a486":{
      "scriptId":"u102"},
    "04cc02ecd3274469ac4153a81fa8acc0":{
      "scriptId":"u103"}}});