$axure.loadCurrentPage({
  "url":"流程说明_1.html",
  "generationDate":new Date(1462500152687.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7fe11978996c4537aa6e12e17ac94e31",
    "type":"Axure:Page",
    "name":"流程说明",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"195b5e311a2e4e0dace60d31801b4f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":40},
            "size":{
              "width":1430,
              "height":1950},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4395df868e874ed9a4283a870f697254",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":40},
                "size":{
                  "width":1430,
                  "height":1950},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u0.png"}},
{
          "id":"6f704db112cf4fe5b18dada0a74f1ef7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":40},
            "size":{
              "width":1430,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1771b6807a04e6f9eda2f1d6991175c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":40},
                "size":{
                  "width":1430,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u2.png"}},
{
          "id":"46ca2b0cc78d4b07a4c68be13763b2ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":570,
              "y":56},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e82a4ef44b488ab9eb43e000d75b69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":570,
                  "y":56},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5f544a0901341b9ab3422f550190007",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":1430,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65459f34f34043d08439a84208a781d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":1430,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF868686}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u6.png"}},
{
          "id":"3ad99b1c1fb9497ea00c06c105fd74e0",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":94},
            "size":{
              "width":10,
              "height":1896},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u8_line.png"}},
{
          "id":"800c759b0e504d41973664989546eeab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":70,
              "y":106},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"661388429f6d4495ae69cb0daecb1998",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":70,
                  "y":106},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"734fcad9799d4edfae221796e2402412",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":590,
              "y":106},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efe15f6c27de487daa35a1326d9e43ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":590,
                  "y":106},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88365aafb6f1460684780a591e91e284",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":80,
              "y":160},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08475e886f804cbdbb3a16e106a8a3ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":80,
                  "y":160},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u13.png"}},
{
          "id":"1f3743cf50e14b80ac9f1ad21f43761a",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":50,
              "y":350},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13b5c7c28c41479f9319d4005c514683",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":50,
                  "y":350},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"cd94d5e5e5124d5699c1c5401ef672cf",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2445227d74d24b87980be7dc28b9431f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"0b4ea57031ea457c8a15222850250990",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":94},
            "size":{
              "width":10,
              "height":1896},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF868686}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u8_line.png"}},
{
          "id":"a4b02dd6147a4e24870d14aa8c2fb002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":1080,
              "y":106},
            "size":{
              "width":230,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f60847ef5114f1c899ab611b947efe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":1080,
                  "y":106},
                "size":{
                  "width":230,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc49fa4543c54cb6877ada7cc0875d82",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":640,
              "y":170},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a249441e8c00409c84d6b313eaabc1a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":640,
                  "y":170},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"866aef7a7eca413f92c694af59be173d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":630,
              "y":520},
            "size":{
              "width":150,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b6069a0b6a647a18cd1a05d0975b266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":630,
                  "y":520},
                "size":{
                  "width":150,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u15.png"}},
{
          "id":"ccbd8eaf5ad7436a8d13afb543c27aaf",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":631,
              "y":720},
            "size":{
              "width":150,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48ffa03adef149b896d119cd4cff8e52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":631,
                  "y":720},
                "size":{
                  "width":150,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u26.png"}},
{
          "id":"1ad215090d344ba1b666032dd59cc6bd",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":472,
              "y":870},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b37cf522f4940b88e51b882832a74c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":472,
                  "y":870},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"960306565d2a45b1b84ad4f5bd14674f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":50,
              "y":510},
            "size":{
              "width":150,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e014302605440f49991b05cbf0c934b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":50,
                  "y":510},
                "size":{
                  "width":150,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u30.png"}},
{
          "id":"bef9f7fbffab4f5b869a21c9658e6eab",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":230},
            "size":{
              "width":10,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u32_line.png"}},
{
          "id":"606eb43b896143398bdb55cec8d04ef3",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":480,
              "y":720},
            "size":{
              "width":134,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ded2e2f27974753a37c06e216ef6307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":480,
                  "y":720},
                "size":{
                  "width":134,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u33.png"}},
{
          "id":"a8e33c99c1b945cab4ff12106b73116f",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"621fe464e34340f9a54b0247810faaa3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"826c4525673b4e5e831ba5ac36f024ce",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":640,
              "y":290},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b135a413e0a4657888f7a4a956014cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":640,
                  "y":290},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"4e8a63ebe10d4ed9a16a39a01fdf3191",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":286},
            "size":{
              "width":120,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6909b387bc414932b54988f7faf06657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":286},
                "size":{
                  "width":120,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u39.png"}},
{
          "id":"418783dad9354d63a9102a06f160a132",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":315},
            "size":{
              "width":260,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/流程说明_1/u41_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u41_line.png"}},
{
          "id":"7c6bec2ef2bb4e1b970f0bdb46e914fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":420,
              "y":300},
            "size":{
              "width":130,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aab708ab91745378608440c65cb1ec7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":420,
                  "y":300},
                "size":{
                  "width":130,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u42.png"}},
{
          "id":"b51004e461e7467aa5083304f4cee522",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":284},
            "size":{
              "width":10,
              "height":391},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u44_line.png"}},
{
          "id":"7d6a1bd54ab34280b8c5394b416b0981",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":356},
            "size":{
              "width":10,
              "height":124},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u45_line.png"}},
{
          "id":"fdae3cafbc8442c8a168ab662d4b82f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":422.5,
              "y":460},
            "size":{
              "width":85,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d2cbf0f38744e80baa8b0bce27bef7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":422.5,
                  "y":460},
                "size":{
                  "width":85,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u46.png"}},
{
          "id":"09c8f863831942519c6ecd5cede43329",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":701,
              "y":478},
            "size":{
              "width":10,
              "height":42},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u48_line.png"}},
{
          "id":"c14f9687fed74e8c98f0c65d83a697d6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":545},
            "size":{
              "width":430,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033CC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/流程说明_1/u41_start.png",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u49_line.png"}},
{
          "id":"c08ece883632491489451a22c56ed53c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":385,
              "y":530},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596227b4ed234cf19f349e2d109e0b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":385,
                  "y":530},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u50.png"}},
{
          "id":"0db5215ecf0c4bbdaff905bb998e1751",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":590},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63fc79ee5c1e4617b43eee048528e62e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":590},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"008cde535ba64334aec87bc7cff4e086",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":580},
            "size":{
              "width":10,
              "height":140},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u54_line.png"}},
{
          "id":"df51e59ae0cc4507a00a8643cfa4fd20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":644,
              "y":630},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bfd7bb73fa74d1fb75b7746d32dd51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":644,
                  "y":630},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u55.png"}},
{
          "id":"9112113bdc8e4c8bb49928f1dbfe9659",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":547,
              "y":790},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee5af3e16fc5456b96c7c4050df1d292",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":547,
                  "y":790},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"eeef31e33c964defaa44def18bf4ffe9",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":260,
              "y":980},
            "size":{
              "width":150,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e0db2f690f4d0ca88944bc54d0cf6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":260,
                  "y":980},
                "size":{
                  "width":150,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u59.png"}},
{
          "id":"807cb2ed7c2b4cf6baaa2b4204605719",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":864},
            "size":{
              "width":10,
              "height":302},
            "rotation":"90",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u61_line.png"}},
{
          "id":"56cb1855df3a4bf3a519693604b6722d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":701,
              "y":790},
            "size":{
              "width":10,
              "height":230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u62_line.png"}},
{
          "id":"676cff032f434505a4b760dcda88f54e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":560,
              "y":995},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d36c99fa8924d51897bd1a6d981e770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":560,
                  "y":995},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u55.png"}},
{
          "id":"16e0c97a78ec4e5baafef3146c54d9fe",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":900},
            "size":{
              "width":10,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u65_line.png"}},
{
          "id":"811d02a497b147f688b9827dc4e43463",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":396,
              "y":829},
            "size":{
              "width":10,
              "height":142},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u66_line.png"}},
{
          "id":"545f1275d1ae41b8a386972039c4f872",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":297.5,
              "y":920},
            "size":{
              "width":75,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f3c1d07716e4012badccacab191cec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":297.5,
                  "y":920},
                "size":{
                  "width":75,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u67.png"}},
{
          "id":"263baa8e056a4cff97da5edeed89539c",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1150,
              "y":170},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23b0da285c1940539a7c4a1033b4b3f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1150,
                  "y":170},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u69.png"}},
{
          "id":"a04f5e3a4fff471b9060035e030b6ecb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1122,
              "y":330},
            "size":{
              "width":155,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1f0df2878764981b1f36935818e3938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1122,
                  "y":330},
                "size":{
                  "width":155,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u71.png"}},
{
          "id":"63eb164d78b74a858a3574662918b40b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a28bc41a11146e4b063cd41e01f7d7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"e8c38788c59d43c895a5861b6dd95482",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1122,
              "y":495},
            "size":{
              "width":155,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"329fe6b26f5743aba10cb5923e317142",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1122,
                  "y":495},
                "size":{
                  "width":155,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u71.png"}},
{
          "id":"5e1be175e10b4abbb95263bdf2dd1bb0",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":390},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c61624bd21934164990f7084f156abed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":390},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"6d3a19adcd814eb5918c9f0b88c6f5fa",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF6666,
              "opacity":1},
            "location":{
              "x":1122,
              "y":650},
            "size":{
              "width":155,
              "height":60},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e96e123572874a5f80aabc327eb4f1bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666,
                  "opacity":1},
                "location":{
                  "x":1122,
                  "y":650},
                "size":{
                  "width":155,
                  "height":60},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u79.png"}},
{
          "id":"055d6a401e494f63bab79558398b3ba4",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":555},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18b62b300f049589ef5c7d855bc77e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":555},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"8d94c56ed86547c9b5d3480056dfd6ea",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":710},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"307ef1547bdb47069306240c1e35de24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":710},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}]},
{
          "id":"24cc377b61994033ad2b925a0ffb8961",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1085.5,
              "y":918.5},
            "size":{
              "width":10,
              "height":63},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/流程说明_1/u32_end.png",
            "line~":"images/流程说明_1/u85_line.png"}},
{
          "id":"a1ec07b5c3f5428aaf72db2908c13e62",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1054,
              "y":523},
            "size":{
              "width":10,
              "height":427},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u86_line.png"}},
{
          "id":"122eea84639c46b3866ac474881ff649",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1085,
              "y":494},
            "size":{
              "width":10,
              "height":62},
            "rotation":"270",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/流程说明_1/u87_line.png"}},
{
          "id":"1d3faadee920444c832b08c36bc47e86",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1122,
              "y":920},
            "size":{
              "width":155,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bce14440d094731a74ec7a4cb46d0d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1122,
                  "y":920},
                "size":{
                  "width":155,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明_1/u71.png"}},
{
          "id":"239a6a9fb00742ce9b497e9a13f43c2e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":1170},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8435ad79d1414e0e88afb3281783aa3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":660,
                  "y":1170},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"aacd2327d50c4c49a1b301fd0fc39f22",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1200,
              "y":980},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0693f36d2dbf4a0ca366c3f1c9febae6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1200,
                  "y":980},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"31870f991fe6436790d49e38941cd9f7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1122,
              "y":1310},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e30e787f9cf412f9cb6c088d7821cb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1122,
                  "y":1310},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"e8df3368fcad44b7b9e0b38c8be68a34",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":735,
              "y":1230},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dbe1f2f0fcc4b4382a1d5098c73b6cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":735,
                  "y":1230},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"5ac5abfa5599406ba310c9ea5cf30b85",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1122,
              "y":1430},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77e6a0344a2248689ff715c4105e2aaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1122,
                  "y":1430},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"b280b939c3d549cd8aad2fbe0ef5d49a",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1197,
              "y":1370},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19a1cb300d73419085db7b35d411deaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1197,
                  "y":1370},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"ce7aecdbc831481bb755b683d3e6cd22",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1122,
              "y":1460},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0033FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42288769b39a462380ba587e9b19018b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1122,
                  "y":1460},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF}},
              "adaptiveStyles":{
}}]},
{
          "id":"04b4422592e649faa9fd58d3515955c7",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":160,
              "y":1430},
            "size":{
              "width":150,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d47a0dad9b094b83aea1f8831e467742",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":160,
                  "y":1430},
                "size":{
                  "width":150,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u28.png"}},
{
          "id":"a1afac866e6c43a3be4ea7c397812750",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":1650},
            "size":{
              "width":420,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6839505561dd4b2bafe1d839bda8375f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":1650},
                "size":{
                  "width":420,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"a8c606416bd745acbc5dffe7393f2b69",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":1674},
            "size":{
              "width":400,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db683581879f4e3a88cd1fb5c22343da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":1674},
                "size":{
                  "width":400,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e0a690d15ae4743bdeeef5f46df9687",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":40,
              "y":1740},
            "size":{
              "width":400,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b68d5bc54e0345f89bfe31e5686aafe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":40,
                  "y":1740},
                "size":{
                  "width":400,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df6980b8914b4a738ba1535dea60e5e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":1650},
            "size":{
              "width":440,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"403e792f2ff94baf9a32b93bcbb315a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":1650},
                "size":{
                  "width":440,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"e17012189e5c4a61806b0922b7bba96b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":520,
              "y":1702},
            "size":{
              "width":400,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb00f41bf7d43eb8e3414d6409f607c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":520,
                  "y":1702},
                "size":{
                  "width":400,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"776f6328f06a4a26b8017509c97d150a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1003,
              "y":1650},
            "size":{
              "width":440,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e17d624f073d4b669b11861944e12c18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1003,
                  "y":1650},
                "size":{
                  "width":440,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程说明/u58.png"}},
{
          "id":"a99928d213664468897279599ad00a46",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1010,
              "y":1674},
            "size":{
              "width":400,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"128248582d534ec6bcda2867612a6c74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1010,
                  "y":1674},
                "size":{
                  "width":400,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "195b5e311a2e4e0dace60d31801b4f47":{
      "scriptId":"u0"},
    "4395df868e874ed9a4283a870f697254":{
      "scriptId":"u1"},
    "6f704db112cf4fe5b18dada0a74f1ef7":{
      "scriptId":"u2"},
    "a1771b6807a04e6f9eda2f1d6991175c":{
      "scriptId":"u3"},
    "46ca2b0cc78d4b07a4c68be13763b2ba":{
      "scriptId":"u4"},
    "74e82a4ef44b488ab9eb43e000d75b69":{
      "scriptId":"u5"},
    "d5f544a0901341b9ab3422f550190007":{
      "scriptId":"u6"},
    "65459f34f34043d08439a84208a781d4":{
      "scriptId":"u7"},
    "3ad99b1c1fb9497ea00c06c105fd74e0":{
      "scriptId":"u8"},
    "800c759b0e504d41973664989546eeab":{
      "scriptId":"u9"},
    "661388429f6d4495ae69cb0daecb1998":{
      "scriptId":"u10"},
    "734fcad9799d4edfae221796e2402412":{
      "scriptId":"u11"},
    "efe15f6c27de487daa35a1326d9e43ba":{
      "scriptId":"u12"},
    "88365aafb6f1460684780a591e91e284":{
      "scriptId":"u13"},
    "08475e886f804cbdbb3a16e106a8a3ee":{
      "scriptId":"u14"},
    "1f3743cf50e14b80ac9f1ad21f43761a":{
      "scriptId":"u15"},
    "13b5c7c28c41479f9319d4005c514683":{
      "scriptId":"u16"},
    "cd94d5e5e5124d5699c1c5401ef672cf":{
      "scriptId":"u17"},
    "2445227d74d24b87980be7dc28b9431f":{
      "scriptId":"u18"},
    "0b4ea57031ea457c8a15222850250990":{
      "scriptId":"u19"},
    "a4b02dd6147a4e24870d14aa8c2fb002":{
      "scriptId":"u20"},
    "7f60847ef5114f1c899ab611b947efe8":{
      "scriptId":"u21"},
    "fc49fa4543c54cb6877ada7cc0875d82":{
      "scriptId":"u22"},
    "a249441e8c00409c84d6b313eaabc1a5":{
      "scriptId":"u23"},
    "866aef7a7eca413f92c694af59be173d":{
      "scriptId":"u24"},
    "9b6069a0b6a647a18cd1a05d0975b266":{
      "scriptId":"u25"},
    "ccbd8eaf5ad7436a8d13afb543c27aaf":{
      "scriptId":"u26"},
    "48ffa03adef149b896d119cd4cff8e52":{
      "scriptId":"u27"},
    "1ad215090d344ba1b666032dd59cc6bd":{
      "scriptId":"u28"},
    "1b37cf522f4940b88e51b882832a74c6":{
      "scriptId":"u29"},
    "960306565d2a45b1b84ad4f5bd14674f":{
      "scriptId":"u30"},
    "3e014302605440f49991b05cbf0c934b":{
      "scriptId":"u31"},
    "bef9f7fbffab4f5b869a21c9658e6eab":{
      "scriptId":"u32"},
    "606eb43b896143398bdb55cec8d04ef3":{
      "scriptId":"u33"},
    "8ded2e2f27974753a37c06e216ef6307":{
      "scriptId":"u34"},
    "a8e33c99c1b945cab4ff12106b73116f":{
      "scriptId":"u35"},
    "621fe464e34340f9a54b0247810faaa3":{
      "scriptId":"u36"},
    "826c4525673b4e5e831ba5ac36f024ce":{
      "scriptId":"u37"},
    "4b135a413e0a4657888f7a4a956014cb":{
      "scriptId":"u38"},
    "4e8a63ebe10d4ed9a16a39a01fdf3191":{
      "scriptId":"u39"},
    "6909b387bc414932b54988f7faf06657":{
      "scriptId":"u40"},
    "418783dad9354d63a9102a06f160a132":{
      "scriptId":"u41"},
    "7c6bec2ef2bb4e1b970f0bdb46e914fa":{
      "scriptId":"u42"},
    "5aab708ab91745378608440c65cb1ec7":{
      "scriptId":"u43"},
    "b51004e461e7467aa5083304f4cee522":{
      "scriptId":"u44"},
    "7d6a1bd54ab34280b8c5394b416b0981":{
      "scriptId":"u45"},
    "fdae3cafbc8442c8a168ab662d4b82f4":{
      "scriptId":"u46"},
    "5d2cbf0f38744e80baa8b0bce27bef7b":{
      "scriptId":"u47"},
    "09c8f863831942519c6ecd5cede43329":{
      "scriptId":"u48"},
    "c14f9687fed74e8c98f0c65d83a697d6":{
      "scriptId":"u49"},
    "c08ece883632491489451a22c56ed53c":{
      "scriptId":"u50"},
    "596227b4ed234cf19f349e2d109e0b46":{
      "scriptId":"u51"},
    "0db5215ecf0c4bbdaff905bb998e1751":{
      "scriptId":"u52"},
    "63fc79ee5c1e4617b43eee048528e62e":{
      "scriptId":"u53"},
    "008cde535ba64334aec87bc7cff4e086":{
      "scriptId":"u54"},
    "df51e59ae0cc4507a00a8643cfa4fd20":{
      "scriptId":"u55"},
    "5bfd7bb73fa74d1fb75b7746d32dd51e":{
      "scriptId":"u56"},
    "9112113bdc8e4c8bb49928f1dbfe9659":{
      "scriptId":"u57"},
    "ee5af3e16fc5456b96c7c4050df1d292":{
      "scriptId":"u58"},
    "eeef31e33c964defaa44def18bf4ffe9":{
      "scriptId":"u59"},
    "14e0db2f690f4d0ca88944bc54d0cf6d":{
      "scriptId":"u60"},
    "807cb2ed7c2b4cf6baaa2b4204605719":{
      "scriptId":"u61"},
    "56cb1855df3a4bf3a519693604b6722d":{
      "scriptId":"u62"},
    "676cff032f434505a4b760dcda88f54e":{
      "scriptId":"u63"},
    "5d36c99fa8924d51897bd1a6d981e770":{
      "scriptId":"u64"},
    "16e0c97a78ec4e5baafef3146c54d9fe":{
      "scriptId":"u65"},
    "811d02a497b147f688b9827dc4e43463":{
      "scriptId":"u66"},
    "545f1275d1ae41b8a386972039c4f872":{
      "scriptId":"u67"},
    "3f3c1d07716e4012badccacab191cec3":{
      "scriptId":"u68"},
    "263baa8e056a4cff97da5edeed89539c":{
      "scriptId":"u69"},
    "23b0da285c1940539a7c4a1033b4b3f7":{
      "scriptId":"u70"},
    "a04f5e3a4fff471b9060035e030b6ecb":{
      "scriptId":"u71"},
    "a1f0df2878764981b1f36935818e3938":{
      "scriptId":"u72"},
    "63eb164d78b74a858a3574662918b40b":{
      "scriptId":"u73"},
    "2a28bc41a11146e4b063cd41e01f7d7f":{
      "scriptId":"u74"},
    "e8c38788c59d43c895a5861b6dd95482":{
      "scriptId":"u75"},
    "329fe6b26f5743aba10cb5923e317142":{
      "scriptId":"u76"},
    "5e1be175e10b4abbb95263bdf2dd1bb0":{
      "scriptId":"u77"},
    "c61624bd21934164990f7084f156abed":{
      "scriptId":"u78"},
    "6d3a19adcd814eb5918c9f0b88c6f5fa":{
      "scriptId":"u79"},
    "e96e123572874a5f80aabc327eb4f1bc":{
      "scriptId":"u80"},
    "055d6a401e494f63bab79558398b3ba4":{
      "scriptId":"u81"},
    "b18b62b300f049589ef5c7d855bc77e6":{
      "scriptId":"u82"},
    "8d94c56ed86547c9b5d3480056dfd6ea":{
      "scriptId":"u83"},
    "307ef1547bdb47069306240c1e35de24":{
      "scriptId":"u84"},
    "24cc377b61994033ad2b925a0ffb8961":{
      "scriptId":"u85"},
    "a1ec07b5c3f5428aaf72db2908c13e62":{
      "scriptId":"u86"},
    "122eea84639c46b3866ac474881ff649":{
      "scriptId":"u87"},
    "1d3faadee920444c832b08c36bc47e86":{
      "scriptId":"u88"},
    "6bce14440d094731a74ec7a4cb46d0d6":{
      "scriptId":"u89"},
    "239a6a9fb00742ce9b497e9a13f43c2e":{
      "scriptId":"u90"},
    "8435ad79d1414e0e88afb3281783aa3b":{
      "scriptId":"u91"},
    "aacd2327d50c4c49a1b301fd0fc39f22":{
      "scriptId":"u92"},
    "0693f36d2dbf4a0ca366c3f1c9febae6":{
      "scriptId":"u93"},
    "31870f991fe6436790d49e38941cd9f7":{
      "scriptId":"u94"},
    "0e30e787f9cf412f9cb6c088d7821cb0":{
      "scriptId":"u95"},
    "e8df3368fcad44b7b9e0b38c8be68a34":{
      "scriptId":"u96"},
    "1dbe1f2f0fcc4b4382a1d5098c73b6cf":{
      "scriptId":"u97"},
    "5ac5abfa5599406ba310c9ea5cf30b85":{
      "scriptId":"u98"},
    "77e6a0344a2248689ff715c4105e2aaa":{
      "scriptId":"u99"},
    "b280b939c3d549cd8aad2fbe0ef5d49a":{
      "scriptId":"u100"},
    "19a1cb300d73419085db7b35d411deaa":{
      "scriptId":"u101"},
    "ce7aecdbc831481bb755b683d3e6cd22":{
      "scriptId":"u102"},
    "42288769b39a462380ba587e9b19018b":{
      "scriptId":"u103"},
    "04b4422592e649faa9fd58d3515955c7":{
      "scriptId":"u104"},
    "d47a0dad9b094b83aea1f8831e467742":{
      "scriptId":"u105"},
    "a1afac866e6c43a3be4ea7c397812750":{
      "scriptId":"u106"},
    "6839505561dd4b2bafe1d839bda8375f":{
      "scriptId":"u107"},
    "a8c606416bd745acbc5dffe7393f2b69":{
      "scriptId":"u108"},
    "db683581879f4e3a88cd1fb5c22343da":{
      "scriptId":"u109"},
    "0e0a690d15ae4743bdeeef5f46df9687":{
      "scriptId":"u110"},
    "b68d5bc54e0345f89bfe31e5686aafe5":{
      "scriptId":"u111"},
    "df6980b8914b4a738ba1535dea60e5e5":{
      "scriptId":"u112"},
    "403e792f2ff94baf9a32b93bcbb315a7":{
      "scriptId":"u113"},
    "e17012189e5c4a61806b0922b7bba96b":{
      "scriptId":"u114"},
    "acb00f41bf7d43eb8e3414d6409f607c":{
      "scriptId":"u115"},
    "776f6328f06a4a26b8017509c97d150a":{
      "scriptId":"u116"},
    "e17d624f073d4b669b11861944e12c18":{
      "scriptId":"u117"},
    "a99928d213664468897279599ad00a46":{
      "scriptId":"u118"},
    "128248582d534ec6bcda2867612a6c74":{
      "scriptId":"u119"}}});