$axure.loadCurrentPage({
  "url":"查看报价单详情.html",
  "generationDate":new Date(1462500152150.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"db4dd8a51c4d404e88f684c45e70773c",
    "type":"Axure:Page",
    "name":"查看报价单详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"73c6358196bb48d49a666f0426eb74f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":140},
            "size":{
              "width":1060,
              "height":1140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed894171b524102831cc609861f3815",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":140},
                "size":{
                  "width":1060,
                  "height":1140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看报价单详情/u0.png"}},
{
          "id":"f71579b0bb004aa581a242e4195ed13f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009966,
              "opacity":1},
            "location":{
              "x":492,
              "y":160},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"778224cb8fac45689b2e7a2cb2ad4c1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009966,
                  "opacity":1},
                "location":{
                  "x":492,
                  "y":160},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ba781f9401d641a9a2cff2da521e52f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":112,
              "y":489},
            "size":{
              "width":1020,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f573cd753404ec69163a1711bf1f236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":112,
                  "y":489},
                "size":{
                  "width":1020,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u6.png"}},
{
          "id":"88bedb4237c5481f84c1c8c52138078e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":122,
              "y":505},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ec36390da66478da3d11f3e7f20ac58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":122,
                  "y":505},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bf19ccc20524efc9e4951911a21238a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":263,
              "y":505},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feaba58380bd47489f9c8b0c98cf7c24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":263,
                  "y":505},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f2231e918304599835396d1a26a5765",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":405,
              "y":505},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4e1198881f041de8c4212d7d7e66176",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":405,
                  "y":505},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b6ae898a61042a7bc1f6fd6dfe7334a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":529,
              "y":505},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c2adee80fb544b8964a8c6e02ac02f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":529,
                  "y":505},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a51f97db6caf480a97000a1ef3da66b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":658,
              "y":505},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33c56c1ede004f50b023e2785ff8394f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":658,
                  "y":505},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"633f093b51c74569bc36ccc1940314de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":791,
              "y":505},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3abd162c40104945bdbd428ec1b7c070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":791,
                  "y":505},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6121f34312eb4803bd1726d6fd095121",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":910,
              "y":505},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ed1a3375734a2e937a7d080892db21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":910,
                  "y":505},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0187a2a769ed4feb950e402c0386c3cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":1022,
              "y":505},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab486743cca1439d8910b259e089aec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":1022,
                  "y":505},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ff22b38fc18b424fb3775e1a5a7fc60a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":539},
            "size":{
              "width":1020,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cca018ccb70c4601ae9e6f9cab09b664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":539},
                "size":{
                  "width":1020,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u24.png"}},
{
          "id":"ce6e9749cc034dee870bcc30d4a4a8fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":122,
              "y":569},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75f408f075f04b81a9e72faf2ae0e78f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":122,
                  "y":569},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acf6668b136a49d39818ade8c8f20bd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":259,
              "y":559},
            "size":{
              "width":120,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7858cf30b60043ad8e21a5f6ffbf3129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":259,
                  "y":559},
                "size":{
                  "width":120,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27bd25d50ad9457eaef6965081427861",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":395,
              "y":569},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfeef74ff0ed4bf4b544b24fd25553f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":395,
                  "y":569},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"437648eab6e644549b1021e5f3235f70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":652,
              "y":571},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5070757eb9cc4927aae2885685245f20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":652,
                  "y":571},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"043853f70e0f4a4c9493de2c8395ca4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":801,
              "y":568},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9389fde6bfe549b9a2caba95b12bd631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":801,
                  "y":568},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"927ea3f4701344299b74a312c91b7331",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":619},
            "size":{
              "width":1020,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"492d27706eb049f1a5b8ac85d64387f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":619},
                "size":{
                  "width":1020,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u24.png"}},
{
          "id":"898b4d05727849f3987eb9bbe9bc7ed1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":259,
              "y":639},
            "size":{
              "width":120,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b364291a5c04cc796a00ecaf37238d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":259,
                  "y":639},
                "size":{
                  "width":120,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fef3778fa04e4441b5215ff2a02f6375",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":395,
              "y":649},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12875776dd4840d796c49496860378e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":395,
                  "y":649},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e14c8a2ebb11419dbada9dbc609826fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":515,
              "y":649},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8680d1c189d42babc2f7c09f6ce1f0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":515,
                  "y":649},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"394c9cba055445f3a447e371ef33fb42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":122,
              "y":645},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfe2d736c06741d8972d49835561d4ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":122,
                  "y":645},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d7e1b684a992401b9aa026cd1c8b0558",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":106,
              "y":811},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d6d1677f5e748a799c3fc92cf58fae1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":106,
                  "y":811},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8325f16cb3f64311a61a313821de6e19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":850},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fabffd754e52453ebc4985ad6aa476f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":850},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a66a09cae7744c49836a5173c126b3a9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":780},
            "size":{
              "width":1060,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/供应商编辑报价单/u64_line.png"}},
{
          "id":"383062adf6654af1a547241c56354a16",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":238,
              "y":940},
            "size":{
              "width":85,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2d82b34a86a4edf83b5e9485909bb80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":238,
                  "y":940},
                "size":{
                  "width":85,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f09fb7606a34b6d8fa256a5660fa70d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":368,
              "y":942},
            "size":{
              "width":140,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4b321bb7ecd49e1bd362beaca71043b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":368,
                  "y":942},
                "size":{
                  "width":140,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4c09d33b7c64c3786ac5160ddf46049",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":432,
              "y":936},
            "size":{
              "width":11,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4725076d4fe45b5b25e1e71865ca166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":432,
                  "y":936},
                "size":{
                  "width":11,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u84.png"}},
{
          "id":"99b56e9bd4454138831ef1645a410604",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":940},
            "size":{
              "width":11,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61d5bcc0043c4eed8f92ee0fcdb81689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":940},
                "size":{
                  "width":11,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u84.png"}},
{
          "id":"1403163a589d4e5eb668c25feb5b5f05",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":1020},
            "size":{
              "width":1060,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/供应商编辑报价单/u64_line.png"}},
{
          "id":"84e21191e34f4a4fb39bc93f481417f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":112,
              "y":230},
            "size":{
              "width":967,
              "height":179}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e647520519d74703bffdc7d68388689d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":112,
                  "y":230},
                "size":{
                  "width":967,
                  "height":179}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看报价单详情/u58.png"}},
{
          "id":"747c7a92ede2420897af43d6d79dfc7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":106,
              "y":424},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae793c5b4c58401fb62573f200e9fd9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":106,
                  "y":424},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4318294733d44e9b336757887d01bb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":515,
              "y":571},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91e497a7feb248a7bbcd941b77b64e61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":515,
                  "y":571},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"315a3116ec35465b9f4c201cf3d50af1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":652,
              "y":645},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d038f9320a7d4f1587e23578f83bbfac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":652,
                  "y":645},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3e204ac85c64bddaa32ab727750d4d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":801,
              "y":645},
            "size":{
              "width":70,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6949e8ce7a5f45d28826de14d73aa674",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":801,
                  "y":645},
                "size":{
                  "width":70,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88cc48fe5e894bbd899440bd230b1c57",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":922,
              "y":564},
            "size":{
              "width":59,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc76feb1dd51477c96bdc36fb7d3325c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":922,
                  "y":564},
                "size":{
                  "width":59,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看报价单详情/u68.png"}},
{
          "id":"26c4b1e34f994ebcaf3453d16063d57c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":926,
              "y":643},
            "size":{
              "width":59,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c510cbc9bb446b084fc57f7a7a31fe1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":926,
                  "y":643},
                "size":{
                  "width":59,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看报价单详情/u68.png"}},
{
          "id":"758c768891d9466493693f3d076ab47f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1002,
              "y":570},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53ea59d4211a498a917f043004cc53a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1002,
                  "y":570},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e44db47fd5934dbfb073596735af1124",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1002,
              "y":650},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e96bf8a44e6442f964e7a844b91e1f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1002,
                  "y":650},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9b25671b9424826885b89dac9e74440",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":580,
              "y":718},
            "size":{
              "width":111,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32bfea81e374436af7c7ca8a44eaec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":580,
                  "y":718},
                "size":{
                  "width":111,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb50dcc57c4548aab129bcdc69ffdc9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":689,
              "y":718},
            "size":{
              "width":71,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64162e1c4db045b992f692308cccfa0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":689,
                  "y":718},
                "size":{
                  "width":71,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39c066a3b35a49c58c16c6320fc46008",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":672,
              "y":714},
            "size":{
              "width":17,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4a6cbb93923426b979425eff5a6b4af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":672,
                  "y":714},
                "size":{
                  "width":17,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看报价单详情/u80.png"}},
{
          "id":"05adf57d7a4740b6bba53c0945bcea3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":788,
              "y":751},
            "size":{
              "width":132,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c503db878da54ef2986348fc50f9c32a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":788,
                  "y":751},
                "size":{
                  "width":132,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c22626878ac14e7089bb6591c5755aa5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":113,
              "y":452},
            "size":{
              "width":288,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aab3c03bd814e0689691392fae4daf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":113,
                  "y":452},
                "size":{
                  "width":288,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看报价单详情/u84.png"}},
{
          "id":"124efb9cad2d41f7abb1d11edd58b791",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":238,
              "y":850},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77b2d9d065dd42b491dbea795634ee8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":238,
                  "y":850},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87f0e05e0b54466480e2c8c91765204d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":352,
              "y":850},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59eb15345c30414c9f434b8504c2fc42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":352,
                  "y":850},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5153ea85c104c0d868d607ca0d890ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":452,
              "y":850},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ce633fd3e4443abb2ebe9f7d3ecc7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":452,
                  "y":850},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37e827dbf4a947e0ae208900bf7b64fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":900},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90a41e2939b64b24ab25007e68cbbcdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":900},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bb142a8413e4ed181973224f6137fc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":238,
              "y":900},
            "size":{
              "width":141,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ad06a4758ee4ca1ac850c060c41767e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":238,
                  "y":900},
                "size":{
                  "width":141,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f77f0049cb25400e981decc590a917d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":940},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"000cc6ee302447eca5aeb9c833cf6782",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":940},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34b40ef5ef294e2bb87c0c8d9186bb88",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":326,
              "y":942},
            "size":{
              "width":53,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886fd297433747478cceaa8deea912e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":326,
                  "y":942},
                "size":{
                  "width":53,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"300aab1b2b914afa96b521c487aab542",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":980},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62ef62b3400542a0a3b0adfe0f957fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":980},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61d5ceee5de94a168a527eb04a6ed12d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":238,
              "y":980},
            "size":{
              "width":141,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a928f7a907f04245b19c948eed18b003",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":238,
                  "y":980},
                "size":{
                  "width":141,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"331f55ca0a7b43339e0ba37a5560aca8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":102,
              "y":1051},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8906321a87d94cdaa9a66e8cfb772ee6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":102,
                  "y":1051},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b90aa212d9dc4c2fb250f4d10e05629c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":1091},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c730e657d0b4f20a4ffdecdc2581aff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":1091},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"276c3a3ca9e04b4eabd5fe0a655c9b24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":262,
              "y":1091},
            "size":{
              "width":141,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afebb61269604da6b48d66f9104d68b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":262,
                  "y":1091},
                "size":{
                  "width":141,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"793a01ed1339463fb7d065b67ad4a413",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":1130},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"585a7eac49794192a6f739f4d93f9a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":1130},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca0757f5d26a4413a4289c355630be95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":259,
              "y":1130},
            "size":{
              "width":213,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf503d1469a34cac8f04606d8dda8bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":259,
                  "y":1130},
                "size":{
                  "width":213,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9976979874244ecf85b919fd62f42856",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":1170},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd31b48318574cb6a193b44ae8f5071f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":1170},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3da4ece93acd48969219ba9e52580de6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":142,
              "y":1210},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8942388b3dc4f8db156faec4d9b16b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":142,
                  "y":1210},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46fa471d78f244d2902887c9a0102930",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":492,
              "y":192},
            "size":{
              "width":200,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0021b110f94a18af5535a88cd89ff5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":492,
                  "y":192},
                "size":{
                  "width":200,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9cd2600415a140cf99ab0d37cdde39e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":770,
              "y":719},
            "size":{
              "width":111,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1cce2f14cccd4c3bb215d8b73dfdea88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":770,
                  "y":719},
                "size":{
                  "width":111,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70838c12fd354c71ba912a725be2a298",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":889,
              "y":717},
            "size":{
              "width":71,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26cb24cefb1f48a6b340cf96edb01cf7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":889,
                  "y":717},
                "size":{
                  "width":71,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6369d1eb42e04eeb92dd41092dd130be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":876,
              "y":715},
            "size":{
              "width":17,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d388065dd7ea4323a9d721c4a0ee434e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":876,
                  "y":715},
                "size":{
                  "width":17,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看报价单详情/u80.png"}},
{
          "id":"8776607d79fe486ca04abc3a7c4dde30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCC0000,
              "opacity":1},
            "location":{
              "x":995,
              "y":719},
            "size":{
              "width":125,
              "height":45},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b73c8e37cfea4989bf55b5f7c831d93b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000,
                  "opacity":1},
                "location":{
                  "x":995,
                  "y":719},
                "size":{
                  "width":125,
                  "height":45},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/查看报价单详情/u126.png"}},
{
          "id":"d68fa42050df437cbd53848c1dbb3d27",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":1360,
              "height":10},
            "borderWidth":"3",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/采购方发布采购单/u72_line.png"}},
{
          "id":"862d7449eb2a4fc6a8290bc6bf559585",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":476,
              "y":46},
            "size":{
              "width":318,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c81367ddccc848f9b0bbb9c4e765afcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":476,
                  "y":46},
                "size":{
                  "width":318,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "73c6358196bb48d49a666f0426eb74f3":{
      "scriptId":"u0"},
    "7ed894171b524102831cc609861f3815":{
      "scriptId":"u1"},
    "f71579b0bb004aa581a242e4195ed13f":{
      "scriptId":"u2"},
    "778224cb8fac45689b2e7a2cb2ad4c1c":{
      "scriptId":"u3"},
    "ba781f9401d641a9a2cff2da521e52f0":{
      "scriptId":"u4"},
    "4f573cd753404ec69163a1711bf1f236":{
      "scriptId":"u5"},
    "88bedb4237c5481f84c1c8c52138078e":{
      "scriptId":"u6"},
    "6ec36390da66478da3d11f3e7f20ac58":{
      "scriptId":"u7"},
    "8bf19ccc20524efc9e4951911a21238a":{
      "scriptId":"u8"},
    "feaba58380bd47489f9c8b0c98cf7c24":{
      "scriptId":"u9"},
    "2f2231e918304599835396d1a26a5765":{
      "scriptId":"u10"},
    "e4e1198881f041de8c4212d7d7e66176":{
      "scriptId":"u11"},
    "7b6ae898a61042a7bc1f6fd6dfe7334a":{
      "scriptId":"u12"},
    "9c2adee80fb544b8964a8c6e02ac02f1":{
      "scriptId":"u13"},
    "a51f97db6caf480a97000a1ef3da66b5":{
      "scriptId":"u14"},
    "33c56c1ede004f50b023e2785ff8394f":{
      "scriptId":"u15"},
    "633f093b51c74569bc36ccc1940314de":{
      "scriptId":"u16"},
    "3abd162c40104945bdbd428ec1b7c070":{
      "scriptId":"u17"},
    "6121f34312eb4803bd1726d6fd095121":{
      "scriptId":"u18"},
    "37ed1a3375734a2e937a7d080892db21":{
      "scriptId":"u19"},
    "0187a2a769ed4feb950e402c0386c3cf":{
      "scriptId":"u20"},
    "ab486743cca1439d8910b259e089aec0":{
      "scriptId":"u21"},
    "ff22b38fc18b424fb3775e1a5a7fc60a":{
      "scriptId":"u22"},
    "cca018ccb70c4601ae9e6f9cab09b664":{
      "scriptId":"u23"},
    "ce6e9749cc034dee870bcc30d4a4a8fb":{
      "scriptId":"u24"},
    "75f408f075f04b81a9e72faf2ae0e78f":{
      "scriptId":"u25"},
    "acf6668b136a49d39818ade8c8f20bd6":{
      "scriptId":"u26"},
    "7858cf30b60043ad8e21a5f6ffbf3129":{
      "scriptId":"u27"},
    "27bd25d50ad9457eaef6965081427861":{
      "scriptId":"u28"},
    "dfeef74ff0ed4bf4b544b24fd25553f3":{
      "scriptId":"u29"},
    "437648eab6e644549b1021e5f3235f70":{
      "scriptId":"u30"},
    "5070757eb9cc4927aae2885685245f20":{
      "scriptId":"u31"},
    "043853f70e0f4a4c9493de2c8395ca4f":{
      "scriptId":"u32"},
    "9389fde6bfe549b9a2caba95b12bd631":{
      "scriptId":"u33"},
    "927ea3f4701344299b74a312c91b7331":{
      "scriptId":"u34"},
    "492d27706eb049f1a5b8ac85d64387f4":{
      "scriptId":"u35"},
    "898b4d05727849f3987eb9bbe9bc7ed1":{
      "scriptId":"u36"},
    "9b364291a5c04cc796a00ecaf37238d5":{
      "scriptId":"u37"},
    "fef3778fa04e4441b5215ff2a02f6375":{
      "scriptId":"u38"},
    "12875776dd4840d796c49496860378e7":{
      "scriptId":"u39"},
    "e14c8a2ebb11419dbada9dbc609826fa":{
      "scriptId":"u40"},
    "a8680d1c189d42babc2f7c09f6ce1f0e":{
      "scriptId":"u41"},
    "394c9cba055445f3a447e371ef33fb42":{
      "scriptId":"u42"},
    "dfe2d736c06741d8972d49835561d4ac":{
      "scriptId":"u43"},
    "d7e1b684a992401b9aa026cd1c8b0558":{
      "scriptId":"u44"},
    "8d6d1677f5e748a799c3fc92cf58fae1":{
      "scriptId":"u45"},
    "8325f16cb3f64311a61a313821de6e19":{
      "scriptId":"u46"},
    "fabffd754e52453ebc4985ad6aa476f7":{
      "scriptId":"u47"},
    "a66a09cae7744c49836a5173c126b3a9":{
      "scriptId":"u48"},
    "383062adf6654af1a547241c56354a16":{
      "scriptId":"u49"},
    "e2d82b34a86a4edf83b5e9485909bb80":{
      "scriptId":"u50"},
    "0f09fb7606a34b6d8fa256a5660fa70d":{
      "scriptId":"u51"},
    "a4b321bb7ecd49e1bd362beaca71043b":{
      "scriptId":"u52"},
    "d4c09d33b7c64c3786ac5160ddf46049":{
      "scriptId":"u53"},
    "c4725076d4fe45b5b25e1e71865ca166":{
      "scriptId":"u54"},
    "99b56e9bd4454138831ef1645a410604":{
      "scriptId":"u55"},
    "61d5bcc0043c4eed8f92ee0fcdb81689":{
      "scriptId":"u56"},
    "1403163a589d4e5eb668c25feb5b5f05":{
      "scriptId":"u57"},
    "84e21191e34f4a4fb39bc93f481417f0":{
      "scriptId":"u58"},
    "e647520519d74703bffdc7d68388689d":{
      "scriptId":"u59"},
    "747c7a92ede2420897af43d6d79dfc7e":{
      "scriptId":"u60"},
    "ae793c5b4c58401fb62573f200e9fd9e":{
      "scriptId":"u61"},
    "b4318294733d44e9b336757887d01bb1":{
      "scriptId":"u62"},
    "91e497a7feb248a7bbcd941b77b64e61":{
      "scriptId":"u63"},
    "315a3116ec35465b9f4c201cf3d50af1":{
      "scriptId":"u64"},
    "d038f9320a7d4f1587e23578f83bbfac":{
      "scriptId":"u65"},
    "c3e204ac85c64bddaa32ab727750d4d6":{
      "scriptId":"u66"},
    "6949e8ce7a5f45d28826de14d73aa674":{
      "scriptId":"u67"},
    "88cc48fe5e894bbd899440bd230b1c57":{
      "scriptId":"u68"},
    "bc76feb1dd51477c96bdc36fb7d3325c":{
      "scriptId":"u69"},
    "26c4b1e34f994ebcaf3453d16063d57c":{
      "scriptId":"u70"},
    "9c510cbc9bb446b084fc57f7a7a31fe1":{
      "scriptId":"u71"},
    "758c768891d9466493693f3d076ab47f":{
      "scriptId":"u72"},
    "53ea59d4211a498a917f043004cc53a4":{
      "scriptId":"u73"},
    "e44db47fd5934dbfb073596735af1124":{
      "scriptId":"u74"},
    "4e96bf8a44e6442f964e7a844b91e1f2":{
      "scriptId":"u75"},
    "c9b25671b9424826885b89dac9e74440":{
      "scriptId":"u76"},
    "c32bfea81e374436af7c7ca8a44eaec0":{
      "scriptId":"u77"},
    "bb50dcc57c4548aab129bcdc69ffdc9b":{
      "scriptId":"u78"},
    "64162e1c4db045b992f692308cccfa0b":{
      "scriptId":"u79"},
    "39c066a3b35a49c58c16c6320fc46008":{
      "scriptId":"u80"},
    "a4a6cbb93923426b979425eff5a6b4af":{
      "scriptId":"u81"},
    "05adf57d7a4740b6bba53c0945bcea3d":{
      "scriptId":"u82"},
    "c503db878da54ef2986348fc50f9c32a":{
      "scriptId":"u83"},
    "c22626878ac14e7089bb6591c5755aa5":{
      "scriptId":"u84"},
    "8aab3c03bd814e0689691392fae4daf2":{
      "scriptId":"u85"},
    "124efb9cad2d41f7abb1d11edd58b791":{
      "scriptId":"u86"},
    "77b2d9d065dd42b491dbea795634ee8b":{
      "scriptId":"u87"},
    "87f0e05e0b54466480e2c8c91765204d":{
      "scriptId":"u88"},
    "59eb15345c30414c9f434b8504c2fc42":{
      "scriptId":"u89"},
    "e5153ea85c104c0d868d607ca0d890ba":{
      "scriptId":"u90"},
    "79ce633fd3e4443abb2ebe9f7d3ecc7b":{
      "scriptId":"u91"},
    "37e827dbf4a947e0ae208900bf7b64fb":{
      "scriptId":"u92"},
    "90a41e2939b64b24ab25007e68cbbcdf":{
      "scriptId":"u93"},
    "4bb142a8413e4ed181973224f6137fc3":{
      "scriptId":"u94"},
    "4ad06a4758ee4ca1ac850c060c41767e":{
      "scriptId":"u95"},
    "f77f0049cb25400e981decc590a917d5":{
      "scriptId":"u96"},
    "000cc6ee302447eca5aeb9c833cf6782":{
      "scriptId":"u97"},
    "34b40ef5ef294e2bb87c0c8d9186bb88":{
      "scriptId":"u98"},
    "886fd297433747478cceaa8deea912e7":{
      "scriptId":"u99"},
    "300aab1b2b914afa96b521c487aab542":{
      "scriptId":"u100"},
    "62ef62b3400542a0a3b0adfe0f957fc3":{
      "scriptId":"u101"},
    "61d5ceee5de94a168a527eb04a6ed12d":{
      "scriptId":"u102"},
    "a928f7a907f04245b19c948eed18b003":{
      "scriptId":"u103"},
    "331f55ca0a7b43339e0ba37a5560aca8":{
      "scriptId":"u104"},
    "8906321a87d94cdaa9a66e8cfb772ee6":{
      "scriptId":"u105"},
    "b90aa212d9dc4c2fb250f4d10e05629c":{
      "scriptId":"u106"},
    "2c730e657d0b4f20a4ffdecdc2581aff":{
      "scriptId":"u107"},
    "276c3a3ca9e04b4eabd5fe0a655c9b24":{
      "scriptId":"u108"},
    "afebb61269604da6b48d66f9104d68b8":{
      "scriptId":"u109"},
    "793a01ed1339463fb7d065b67ad4a413":{
      "scriptId":"u110"},
    "585a7eac49794192a6f739f4d93f9a2d":{
      "scriptId":"u111"},
    "ca0757f5d26a4413a4289c355630be95":{
      "scriptId":"u112"},
    "cf503d1469a34cac8f04606d8dda8bdf":{
      "scriptId":"u113"},
    "9976979874244ecf85b919fd62f42856":{
      "scriptId":"u114"},
    "fd31b48318574cb6a193b44ae8f5071f":{
      "scriptId":"u115"},
    "3da4ece93acd48969219ba9e52580de6":{
      "scriptId":"u116"},
    "e8942388b3dc4f8db156faec4d9b16b7":{
      "scriptId":"u117"},
    "46fa471d78f244d2902887c9a0102930":{
      "scriptId":"u118"},
    "0f0021b110f94a18af5535a88cd89ff5":{
      "scriptId":"u119"},
    "9cd2600415a140cf99ab0d37cdde39e3":{
      "scriptId":"u120"},
    "1cce2f14cccd4c3bb215d8b73dfdea88":{
      "scriptId":"u121"},
    "70838c12fd354c71ba912a725be2a298":{
      "scriptId":"u122"},
    "26cb24cefb1f48a6b340cf96edb01cf7":{
      "scriptId":"u123"},
    "6369d1eb42e04eeb92dd41092dd130be":{
      "scriptId":"u124"},
    "d388065dd7ea4323a9d721c4a0ee434e":{
      "scriptId":"u125"},
    "8776607d79fe486ca04abc3a7c4dde30":{
      "scriptId":"u126"},
    "b73c8e37cfea4989bf55b5f7c831d93b":{
      "scriptId":"u127"},
    "d68fa42050df437cbd53848c1dbb3d27":{
      "scriptId":"u128"},
    "862d7449eb2a4fc6a8290bc6bf559585":{
      "scriptId":"u129"},
    "c81367ddccc848f9b0bbb9c4e765afcc":{
      "scriptId":"u130"}}});