$axure.loadCurrentPage({
  "url":"商详页示意图.html",
  "generationDate":new Date(1462500153729.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dcfe72cb4b8243df98d38d7dbc115c75",
    "type":"Axure:Page",
    "name":"商详页示意图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"25dffd478e874d48a486e350ddfcbd6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1271,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26acd24e0ecf4c1887a28726a23f57be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1271,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页选购商品示意/u2.png"}},
{
          "id":"d7af034364e8481caf444f6a01b23026",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":186},
            "size":{
              "width":368,
              "height":464}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4208cfba0aa4fe184f92f022315af2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":186},
                "size":{
                  "width":368,
                  "height":464}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u2.png"}},
{
          "id":"35e5a77e83b64c82a1c39f6f4181948a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":194},
            "size":{
              "width":499,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46b034e03114fb89b37a3f69f675494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":194},
                "size":{
                  "width":499,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u4.png"}},
{
          "id":"68ff7268965847e49fb68d7a7fb81419",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":435.5,
              "y":372},
            "size":{
              "width":556,
              "height":50},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d0085f354c34320b9e1db1126c9d7b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":435.5,
                  "y":372},
                "size":{
                  "width":556,
                  "height":50},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u6.png"}},
{
          "id":"57053f2ff19e439585860889fc9aa5b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1014,
              "y":186},
            "size":{
              "width":246,
              "height":418}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b6fc0a597404368807535d8a288c1fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1014,
                  "y":186},
                "size":{
                  "width":246,
                  "height":418}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u8.png"}},
{
          "id":"cac864f1d24b4fcdb80507ad224d6feb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":428,
              "y":264},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"918737f7ee6d4c24a21fad51b2308650",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":428,
                  "y":264},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9fa4c235093467c88aa9766ff9ace7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":260},
            "size":{
              "width":405,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89d86b580b804148918b376a6728c1e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":260},
                "size":{
                  "width":405,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u12.png"}},
{
          "id":"67a43afefa014273afdc4e8ca5a39a15",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":250},
            "size":{
              "width":576,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商详页示意图/u14_line.png"}},
{
          "id":"f6fd482101fd4c7a8c96d1fcec7385a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":428,
              "y":299},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58ea08704abc4d3d832564bbf5d3887a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":428,
                  "y":299},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40ca6a5e062642d0979bac3e0254ad8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":515,
              "y":299},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c430c5b6cf2485dbc077959461b669b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":515,
                  "y":299},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0b892d9bd58340128369445f11c6a56b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":428,
              "y":326},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31da0b0e957f4adda5d2e6bf5c7ee34c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":428,
                  "y":326},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"653fcf200231415dbb856deafe13ae7a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":319},
            "size":{
              "width":177,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd68d1800a31439d965b0b8adc7833af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":319},
                "size":{
                  "width":177,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u21.png"}},
{
          "id":"3ebef3c7aad740f9bc139bc60ea75671",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":425.5,
              "y":352},
            "size":{
              "width":576,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商详页示意图/u14_line.png"}},
{
          "id":"ace91661c507474bbee09afe0e39741c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":426,
              "y":412},
            "size":{
              "width":576,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/商详页示意图/u14_line.png"}},
{
          "id":"457b8fff89e14ac684ca60f466773c83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":436,
              "y":450},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ecde7dd67c7423d9ec916fceda8b817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":436,
                  "y":450},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f17f8a4fffc4241be925d1a5347904a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":450},
            "size":{
              "width":172,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"271155094ddc492aa25ae5905ca1e1db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":702,
              "y":452},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcaa6bfbf60847adaabc3bc6270dfa12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":702,
                  "y":452},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0147b3461af04fe4ba9684ca62514d2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":436,
              "y":515},
            "size":{
              "width":112,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7129c24ae45346539fdfb3f7007609a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":436,
                  "y":515},
                "size":{
                  "width":112,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"485445184b6c407891470b87c1e7baa1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":515},
            "size":{
              "width":172,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c02c5d78e8e9491fabda4f1cec804a61",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":590},
            "size":{
              "width":225,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b992a807e89342268b5c3a1a030496cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":450,
                  "y":590},
                "size":{
                  "width":225,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u33.png"}},
{
          "id":"6f05882ec40f48d0a041a0d2b1f606d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":702,
              "y":515},
            "size":{
              "width":138,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b2e3de686740eaa6a3b87f81286f1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":702,
                  "y":515},
                "size":{
                  "width":138,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82f0dca7ed9244478dcdadd474d88fc4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":688},
            "size":{
              "width":989,
              "height":942}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"873dc9684f094dc1a4ff8cc97ce81169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":688},
                "size":{
                  "width":989,
                  "height":942}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页示意图/u37.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "25dffd478e874d48a486e350ddfcbd6c":{
      "scriptId":"u0"},
    "26acd24e0ecf4c1887a28726a23f57be":{
      "scriptId":"u1"},
    "d7af034364e8481caf444f6a01b23026":{
      "scriptId":"u2"},
    "d4208cfba0aa4fe184f92f022315af2b":{
      "scriptId":"u3"},
    "35e5a77e83b64c82a1c39f6f4181948a":{
      "scriptId":"u4"},
    "b46b034e03114fb89b37a3f69f675494":{
      "scriptId":"u5"},
    "68ff7268965847e49fb68d7a7fb81419":{
      "scriptId":"u6"},
    "9d0085f354c34320b9e1db1126c9d7b8":{
      "scriptId":"u7"},
    "57053f2ff19e439585860889fc9aa5b0":{
      "scriptId":"u8"},
    "5b6fc0a597404368807535d8a288c1fc":{
      "scriptId":"u9"},
    "cac864f1d24b4fcdb80507ad224d6feb":{
      "scriptId":"u10"},
    "918737f7ee6d4c24a21fad51b2308650":{
      "scriptId":"u11"},
    "e9fa4c235093467c88aa9766ff9ace7e":{
      "scriptId":"u12"},
    "89d86b580b804148918b376a6728c1e6":{
      "scriptId":"u13"},
    "67a43afefa014273afdc4e8ca5a39a15":{
      "scriptId":"u14"},
    "f6fd482101fd4c7a8c96d1fcec7385a3":{
      "scriptId":"u15"},
    "58ea08704abc4d3d832564bbf5d3887a":{
      "scriptId":"u16"},
    "40ca6a5e062642d0979bac3e0254ad8e":{
      "scriptId":"u17"},
    "0c430c5b6cf2485dbc077959461b669b":{
      "scriptId":"u18"},
    "0b892d9bd58340128369445f11c6a56b":{
      "scriptId":"u19"},
    "31da0b0e957f4adda5d2e6bf5c7ee34c":{
      "scriptId":"u20"},
    "653fcf200231415dbb856deafe13ae7a":{
      "scriptId":"u21"},
    "bd68d1800a31439d965b0b8adc7833af":{
      "scriptId":"u22"},
    "3ebef3c7aad740f9bc139bc60ea75671":{
      "scriptId":"u23"},
    "ace91661c507474bbee09afe0e39741c":{
      "scriptId":"u24"},
    "457b8fff89e14ac684ca60f466773c83":{
      "scriptId":"u25"},
    "5ecde7dd67c7423d9ec916fceda8b817":{
      "scriptId":"u26"},
    "4f17f8a4fffc4241be925d1a5347904a":{
      "scriptId":"u27"},
    "271155094ddc492aa25ae5905ca1e1db":{
      "scriptId":"u28"},
    "dcaa6bfbf60847adaabc3bc6270dfa12":{
      "scriptId":"u29"},
    "0147b3461af04fe4ba9684ca62514d2f":{
      "scriptId":"u30"},
    "7129c24ae45346539fdfb3f7007609a3":{
      "scriptId":"u31"},
    "485445184b6c407891470b87c1e7baa1":{
      "scriptId":"u32"},
    "c02c5d78e8e9491fabda4f1cec804a61":{
      "scriptId":"u33"},
    "b992a807e89342268b5c3a1a030496cd":{
      "scriptId":"u34"},
    "6f05882ec40f48d0a041a0d2b1f606d1":{
      "scriptId":"u35"},
    "28b2e3de686740eaa6a3b87f81286f1f":{
      "scriptId":"u36"},
    "82f0dca7ed9244478dcdadd474d88fc4":{
      "scriptId":"u37"},
    "873dc9684f094dc1a4ff8cc97ce81169":{
      "scriptId":"u38"}}});