$axure.loadCurrentPage({
  "url":"个性化备注页面.html",
  "generationDate":new Date(1462500153107.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3ddc362e36824c6994004317a6d597da",
    "type":"Axure:Page",
    "name":"个性化备注页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7e6d11c3c7ce4d45a83291f2b1d4f921",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1271,
              "height":176}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a966a6e885d5404ab6bfc33b482631c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1271,
                  "height":176}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商详页选购商品示意/u2.png"}},
{
          "id":"d01238ce15ce4e51b6e56ee1fe026e1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":176},
            "size":{
              "width":1210,
              "height":1704},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04fbb3df22ed4e949ae2af8550b8941b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":176},
                "size":{
                  "width":1210,
                  "height":1704},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个性化备注页面/u2.png"}},
{
          "id":"559ce62e449944fcb45d61acfd9a3bdc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":452,
              "y":206},
            "size":{
              "width":280,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae43d60395c42c8a49c33ebd64a8318",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":452,
                  "y":206},
                "size":{
                  "width":280,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60b81084ebd641ac988d702d903468c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":270},
            "size":{
              "width":1210,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a14049653014393be291fcdacb69eed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":270},
                "size":{
                  "width":1210,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个性化备注页面/u6.png"}},
{
          "id":"905ab3ac0271432291c377c328013a57",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":70,
              "y":287},
            "size":{
              "width":150,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d017e2c553a47fea748e4629f02361d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":70,
                  "y":287},
                "size":{
                  "width":150,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dce9707762344e8bab8ab6a9620f066c",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":110,
              "y":341},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ebca71e2d164bcc91282485a3872bc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":110,
                  "y":341},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"Case 1<br> (If 选中状态于 This == true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 文案详情",
                      "objectsToFades":[{
                          "objectPath":["ace16d34e60a495ca9113bc865e03bbc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 文案详情 为 统一定制",
                      "panelsToStates":[{
                          "panelPath":["ace16d34e60a495ca9113bc865e03bbc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"b4d72e25619340eb8556b888e2b0ee94",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":290,
              "y":341},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9f27ccfc85e4f83b9b1899373a69768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":290,
                  "y":341},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onCheckedChange":{
              "description":"OnCheckedChange",
              "cases":[{
                  "description":"Case 1<br> (If 选中状态于 This == true)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"booleanLiteral",
                      "value":true}},
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 文案详情",
                      "objectsToFades":[{
                          "objectPath":["ace16d34e60a495ca9113bc865e03bbc"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 文案详情 为 不同商品定制",
                      "panelsToStates":[{
                          "panelPath":["ace16d34e60a495ca9113bc865e03bbc"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"909a34ab7bb646e39bf3874383a54610",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":400},
            "size":{
              "width":1210,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90bf9c21b9204295a8d4eabc7b22cbdb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":400},
                "size":{
                  "width":1210,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个性化备注页面/u6.png"}},
{
          "id":"d089d9507df740de8f13506d48f5e8a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":70,
              "y":417},
            "size":{
              "width":150,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d97db55d71114de383d5272c6034b455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":70,
                  "y":417},
                "size":{
                  "width":150,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ace16d34e60a495ca9113bc865e03bbc",
          "label":"文案详情",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":488},
            "size":{
              "width":1050,
              "height":1362}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"43d6b1f1bf7e435996d87edd59445dbf",
              "label":"统一定制",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"832a98998e644efa9915cf37f8e5dba2",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":3},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa58a00421ce4c6ca440969e7d1f6892",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":3},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2de05497e155415881b363595de9151a",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":0},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"f403900cc08c4d7f94a42b3931f1f959",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":43},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a352a809be46429e889aa679908f76c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":43},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c960c2880324bb986bfd830b6c78d5a",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":43},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"61ab1a4f1f1945f0a79f220a6492cab3",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a23036a087df460bb7a9169e5139bc94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":92},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ff476576fa384828ab06caf71e4a0292",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":92},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 颜色卡",
                              "objectsToFades":[{
                                  "objectPath":["a2af72f35fa8406eb8f80ca903d81f50"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]},
                    "onLostFocus":{
                      "description":"OnLostFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 颜色卡",
                              "objectsToFades":[{
                                  "objectPath":["a2af72f35fa8406eb8f80ca903d81f50"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"e75b2c44f7cc418481d072d15fcb127f",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":0,
                      "y":142},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7b66c2593514907b5c9f83730c0968c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":0,
                          "y":142},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9b421469acc84f5f9f8a7fe61b405c36",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":90,
                      "y":136},
                    "size":{
                      "width":120,
                      "height":30},
                    "cornerRadiusTopLeft":"7"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"805f07bc9ac540f4916f29f234a07134",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":90,
                          "y":136},
                        "size":{
                          "width":120,
                          "height":30},
                        "cornerRadiusTopLeft":"7"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u30.png"}},
{
                  "id":"98d40a726ba44a3d8252b98bdc918957",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":176},
                    "size":{
                      "width":350,
                      "height":176}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1bb7af8e18b64da299e429ae66c41e7f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":176},
                        "size":{
                          "width":350,
                          "height":176}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u32.png"}},
{
                  "id":"a2af72f35fa8406eb8f80ca903d81f50",
                  "label":"颜色卡",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":150,
                      "y":117},
                    "size":{
                      "width":259,
                      "height":171},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9bba02723514fe9834c09053e8ade26",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":150,
                          "y":117},
                        "size":{
                          "width":259,
                          "height":171},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/颜色卡_u34.png"}},
{
                  "id":"21244e2aef7f400fb089f991897d7027",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":383},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"250882f8f6b543e296acd1d4c2773f6f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":383},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"86f9660f8363426c9cf191b75c238d1f",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":376},
                    "size":{
                      "width":350,
                      "height":176}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"042f406fa9694ab6baeca954c014d134",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":90,
                          "y":376},
                        "size":{
                          "width":350,
                          "height":176}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u32.png"}},
{
                  "id":"2c3771348f3740cd8311a8c37fd651ed",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":220,
                      "y":690},
                    "size":{
                      "width":110,
                      "height":40},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7984e382793b42a6801a7cc344958f4c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":220,
                          "y":690},
                        "size":{
                          "width":110,
                          "height":40},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"closeCurrent",
                              "description":"关闭当前窗口"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/个性化备注页面/u40.png"}},
{
                  "id":"96b9f5a931b9417fb7a9758f9ed701f4",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":480,
                      "y":690},
                    "size":{
                      "width":110,
                      "height":40},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"803ff361cb7d43ce8597f5f5b3b471c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":480,
                          "y":690},
                        "size":{
                          "width":110,
                          "height":40},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"closeCurrent",
                              "description":"关闭当前窗口"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/个性化备注页面/u40.png"}}]},
{
              "id":"79f3fd031b9348809f17f83ac53b73fd",
              "label":"不同商品定制",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"23f5cf85a05e49dcab410e12385fc804",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":40,
                      "y":63},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f036c62921c243d4bc17be39b3310b1d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":40,
                          "y":63},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8f5b214637d049c7b0902bc0be477a06",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":60},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"4c2b1126bff64b39a888b01a6a4130f2",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":40,
                      "y":103},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"49426659ed5c45b09d27e58e0d012f5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":40,
                          "y":103},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f43d272b73294017bdd3896029752bd4",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":103},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"10b7b94624844cfc8cce177f5023e7dc",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":40,
                      "y":152},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d664a7c77cc848acb3cbe4dde1098063",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":40,
                          "y":152},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"206aeccafbda45d3b38ef8aba93f8a8c",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":152},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 颜色卡",
                              "objectsToFades":[{
                                  "objectPath":["8efb05e30d534af2be07de6856ceebf2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]},
                    "onLostFocus":{
                      "description":"OnLostFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 颜色卡",
                              "objectsToFades":[{
                                  "objectPath":["8efb05e30d534af2be07de6856ceebf2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"01aa1d2537074ac0a4df8911302838ac",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":40,
                      "y":202},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"810d270192fa498fbec7118955e468c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":40,
                          "y":202},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c689c1a6217b4642afc7da8f675b01c0",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":130,
                      "y":196},
                    "size":{
                      "width":120,
                      "height":30},
                    "cornerRadiusTopLeft":"7"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ede01928471441bbcde24cf71799d5d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":130,
                          "y":196},
                        "size":{
                          "width":120,
                          "height":30},
                        "cornerRadiusTopLeft":"7"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u30.png"}},
{
                  "id":"bd12a28e32164c8f8c2ec74160a4a155",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":236},
                    "size":{
                      "width":350,
                      "height":176}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4dda7fd30d644d98c8f777d8526318c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":236},
                        "size":{
                          "width":350,
                          "height":176}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u32.png"}},
{
                  "id":"8efb05e30d534af2be07de6856ceebf2",
                  "label":"颜色卡",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":190,
                      "y":177},
                    "size":{
                      "width":259,
                      "height":171},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"315ecd8b76274b99a6f04d0c9f617df7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":190,
                          "y":177},
                        "size":{
                          "width":259,
                          "height":171},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/颜色卡_u34.png"}},
{
                  "id":"d148b1d70c2940a78d8a786fc711f306",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":40,
                      "y":443},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40a999b1a3d0429792699e2522524dc1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":40,
                          "y":443},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2c6203c4c235465ea66895ee3502c663",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":436},
                    "size":{
                      "width":350,
                      "height":176}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b00093fd20944f50994ca8712fa8bfec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":436},
                        "size":{
                          "width":350,
                          "height":176}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u32.png"}},
{
                  "id":"af90f59c3a594831a4bd254623b7df20",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xD6F2F2F2},
                    "location":{
                      "x":0,
                      "y":3},
                    "size":{
                      "width":1040,
                      "height":47},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c13fed62bad4fe2b2ffa8d16e705333",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xD6F2F2F2},
                        "location":{
                          "x":0,
                          "y":3},
                        "size":{
                          "width":1040,
                          "height":47},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u65.png"}},
{
                  "id":"1f0c8376f53e42369dfd406ce52dc346",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":20,
                      "y":18},
                    "size":{
                      "width":300,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"214aa4a9504343b28d001879a5a17033",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":20,
                          "y":18},
                        "size":{
                          "width":300,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3e71fa6e86bb488db0a20910f23c93f6",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xD6F2F2F2},
                    "location":{
                      "x":0,
                      "y":637},
                    "size":{
                      "width":1040,
                      "height":47},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFBCBCBC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0728897985b548dc8a03cca3a24f0989",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xD6F2F2F2},
                        "location":{
                          "x":0,
                          "y":637},
                        "size":{
                          "width":1040,
                          "height":47},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFBCBCBC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u65.png"}},
{
                  "id":"7e3ee0f70e9e4ebbae347c268ece8c15",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "location":{
                      "x":20,
                      "y":652},
                    "size":{
                      "width":300,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9eb724835e9047e9ba97bc48a7136fba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "location":{
                          "x":20,
                          "y":652},
                        "size":{
                          "width":300,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ee3ba53de6f244bf8de90c94749bf9f5",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":40,
                      "y":700},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62099559ab1a45208d95f894bcdf0798",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":40,
                          "y":700},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d7169d515c8642ba882ceceb8b7e3648",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":697},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"a7005ea4ec844597ac056cfcba6c576d",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":40,
                      "y":740},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"440a1b303c5d48dbb2df6449aaa8ff8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":40,
                          "y":740},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3de0a7ecf7c482fb2e04f3338f3d7aa",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":740},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"8e02818f14e344bb99d930c4aa64b5b2",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":40,
                      "y":789},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"70b513c1133b4cc484e91703e6e5a39c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":40,
                          "y":789},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"93de88bea8574ad98469a9e698e44e86",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":789},
                    "size":{
                      "width":350,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onFocus":{
                      "description":"OnFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 颜色卡",
                              "objectsToFades":[{
                                  "objectPath":["66d80d3369d84f4bbcbd53e5fe162882"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]},
                    "onLostFocus":{
                      "description":"OnLostFocus",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 颜色卡",
                              "objectsToFades":[{
                                  "objectPath":["66d80d3369d84f4bbcbd53e5fe162882"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"e93cf2aaea0c40b296b2696de523acd7",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":40,
                      "y":839},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4c48aee53304cd4a079ac191e7c9036",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":40,
                          "y":839},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b2fd9e0ae048403da576448ab61035fc",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":130,
                      "y":833},
                    "size":{
                      "width":120,
                      "height":30},
                    "cornerRadiusTopLeft":"7"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"90133a309460446fb8b3592f27a6d860",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":130,
                          "y":833},
                        "size":{
                          "width":120,
                          "height":30},
                        "cornerRadiusTopLeft":"7"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u30.png"}},
{
                  "id":"e24d40c775c04e8c8adab7a43a6fbeab",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":873},
                    "size":{
                      "width":350,
                      "height":176}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55e1e5816e05404c8b1de1df8f277726",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":873},
                        "size":{
                          "width":350,
                          "height":176}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u32.png"}},
{
                  "id":"66d80d3369d84f4bbcbd53e5fe162882",
                  "label":"颜色卡",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":190,
                      "y":814},
                    "size":{
                      "width":259,
                      "height":171},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10b461ef2e8a4d09bc1ce5db66c7b7e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":190,
                          "y":814},
                        "size":{
                          "width":259,
                          "height":171},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/颜色卡_u34.png"}},
{
                  "id":"58333d1149e64c7e880e44bfb2bf0c8f",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":40,
                      "y":1080},
                    "size":{
                      "width":100,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5eaec3cda9ac4138ae66bec900b870dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "location":{
                          "x":40,
                          "y":1080},
                        "size":{
                          "width":100,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"17ca9f8986c74275b90b301c29e7971b",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":1073},
                    "size":{
                      "width":350,
                      "height":176}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"595f455376234772b246378d8de6de3c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":130,
                          "y":1073},
                        "size":{
                          "width":350,
                          "height":176}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个性化备注页面/u32.png"}},
{
                  "id":"64cb0777fe704f14b9c15ccff4db2620",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":270,
                      "y":1300},
                    "size":{
                      "width":110,
                      "height":40},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a73ba12866554f90881ad5a585afbbf3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":270,
                          "y":1300},
                        "size":{
                          "width":110,
                          "height":40},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"closeCurrent",
                              "description":"关闭当前窗口"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/个性化备注页面/u40.png"}},
{
                  "id":"410073dbbfa34ed48ce4006dd7509cef",
                  "label":"",
                  "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":530,
                      "y":1300},
                    "size":{
                      "width":110,
                      "height":40},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b905d8d7e6ad4ca89d63a6c0840dce00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"ace16d34e60a495ca9113bc865e03bbc",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":530,
                          "y":1300},
                        "size":{
                          "width":110,
                          "height":40},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"closeCurrent",
                              "description":"关闭当前窗口"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/个性化备注页面/u40.png"}}]}]},
{
          "id":"3333fdedf7694c3f94d3219d20bc99ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":280,
              "y":734},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e26dc6fe5655499fb5035f72f19952ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":280,
                  "y":734},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7e6d11c3c7ce4d45a83291f2b1d4f921":{
      "scriptId":"u0"},
    "a966a6e885d5404ab6bfc33b482631c4":{
      "scriptId":"u1"},
    "d01238ce15ce4e51b6e56ee1fe026e1d":{
      "scriptId":"u2"},
    "04fbb3df22ed4e949ae2af8550b8941b":{
      "scriptId":"u3"},
    "559ce62e449944fcb45d61acfd9a3bdc":{
      "scriptId":"u4"},
    "1ae43d60395c42c8a49c33ebd64a8318":{
      "scriptId":"u5"},
    "60b81084ebd641ac988d702d903468c6":{
      "scriptId":"u6"},
    "3a14049653014393be291fcdacb69eed":{
      "scriptId":"u7"},
    "905ab3ac0271432291c377c328013a57":{
      "scriptId":"u8"},
    "3d017e2c553a47fea748e4629f02361d":{
      "scriptId":"u9"},
    "dce9707762344e8bab8ab6a9620f066c":{
      "scriptId":"u10"},
    "2ebca71e2d164bcc91282485a3872bc2":{
      "scriptId":"u11"},
    "b4d72e25619340eb8556b888e2b0ee94":{
      "scriptId":"u12"},
    "a9f27ccfc85e4f83b9b1899373a69768":{
      "scriptId":"u13"},
    "909a34ab7bb646e39bf3874383a54610":{
      "scriptId":"u14"},
    "90bf9c21b9204295a8d4eabc7b22cbdb":{
      "scriptId":"u15"},
    "d089d9507df740de8f13506d48f5e8a3":{
      "scriptId":"u16"},
    "d97db55d71114de383d5272c6034b455":{
      "scriptId":"u17"},
    "ace16d34e60a495ca9113bc865e03bbc":{
      "scriptId":"u18"},
    "832a98998e644efa9915cf37f8e5dba2":{
      "scriptId":"u19"},
    "fa58a00421ce4c6ca440969e7d1f6892":{
      "scriptId":"u20"},
    "2de05497e155415881b363595de9151a":{
      "scriptId":"u21"},
    "f403900cc08c4d7f94a42b3931f1f959":{
      "scriptId":"u22"},
    "a352a809be46429e889aa679908f76c0":{
      "scriptId":"u23"},
    "0c960c2880324bb986bfd830b6c78d5a":{
      "scriptId":"u24"},
    "61ab1a4f1f1945f0a79f220a6492cab3":{
      "scriptId":"u25"},
    "a23036a087df460bb7a9169e5139bc94":{
      "scriptId":"u26"},
    "ff476576fa384828ab06caf71e4a0292":{
      "scriptId":"u27"},
    "e75b2c44f7cc418481d072d15fcb127f":{
      "scriptId":"u28"},
    "c7b66c2593514907b5c9f83730c0968c":{
      "scriptId":"u29"},
    "9b421469acc84f5f9f8a7fe61b405c36":{
      "scriptId":"u30"},
    "805f07bc9ac540f4916f29f234a07134":{
      "scriptId":"u31"},
    "98d40a726ba44a3d8252b98bdc918957":{
      "scriptId":"u32"},
    "1bb7af8e18b64da299e429ae66c41e7f":{
      "scriptId":"u33"},
    "a2af72f35fa8406eb8f80ca903d81f50":{
      "scriptId":"u34"},
    "e9bba02723514fe9834c09053e8ade26":{
      "scriptId":"u35"},
    "21244e2aef7f400fb089f991897d7027":{
      "scriptId":"u36"},
    "250882f8f6b543e296acd1d4c2773f6f":{
      "scriptId":"u37"},
    "86f9660f8363426c9cf191b75c238d1f":{
      "scriptId":"u38"},
    "042f406fa9694ab6baeca954c014d134":{
      "scriptId":"u39"},
    "2c3771348f3740cd8311a8c37fd651ed":{
      "scriptId":"u40"},
    "7984e382793b42a6801a7cc344958f4c":{
      "scriptId":"u41"},
    "96b9f5a931b9417fb7a9758f9ed701f4":{
      "scriptId":"u42"},
    "803ff361cb7d43ce8597f5f5b3b471c6":{
      "scriptId":"u43"},
    "23f5cf85a05e49dcab410e12385fc804":{
      "scriptId":"u44"},
    "f036c62921c243d4bc17be39b3310b1d":{
      "scriptId":"u45"},
    "8f5b214637d049c7b0902bc0be477a06":{
      "scriptId":"u46"},
    "4c2b1126bff64b39a888b01a6a4130f2":{
      "scriptId":"u47"},
    "49426659ed5c45b09d27e58e0d012f5d":{
      "scriptId":"u48"},
    "f43d272b73294017bdd3896029752bd4":{
      "scriptId":"u49"},
    "10b7b94624844cfc8cce177f5023e7dc":{
      "scriptId":"u50"},
    "d664a7c77cc848acb3cbe4dde1098063":{
      "scriptId":"u51"},
    "206aeccafbda45d3b38ef8aba93f8a8c":{
      "scriptId":"u52"},
    "01aa1d2537074ac0a4df8911302838ac":{
      "scriptId":"u53"},
    "810d270192fa498fbec7118955e468c1":{
      "scriptId":"u54"},
    "c689c1a6217b4642afc7da8f675b01c0":{
      "scriptId":"u55"},
    "2ede01928471441bbcde24cf71799d5d":{
      "scriptId":"u56"},
    "bd12a28e32164c8f8c2ec74160a4a155":{
      "scriptId":"u57"},
    "e4dda7fd30d644d98c8f777d8526318c":{
      "scriptId":"u58"},
    "8efb05e30d534af2be07de6856ceebf2":{
      "scriptId":"u59"},
    "315ecd8b76274b99a6f04d0c9f617df7":{
      "scriptId":"u60"},
    "d148b1d70c2940a78d8a786fc711f306":{
      "scriptId":"u61"},
    "40a999b1a3d0429792699e2522524dc1":{
      "scriptId":"u62"},
    "2c6203c4c235465ea66895ee3502c663":{
      "scriptId":"u63"},
    "b00093fd20944f50994ca8712fa8bfec":{
      "scriptId":"u64"},
    "af90f59c3a594831a4bd254623b7df20":{
      "scriptId":"u65"},
    "9c13fed62bad4fe2b2ffa8d16e705333":{
      "scriptId":"u66"},
    "1f0c8376f53e42369dfd406ce52dc346":{
      "scriptId":"u67"},
    "214aa4a9504343b28d001879a5a17033":{
      "scriptId":"u68"},
    "3e71fa6e86bb488db0a20910f23c93f6":{
      "scriptId":"u69"},
    "0728897985b548dc8a03cca3a24f0989":{
      "scriptId":"u70"},
    "7e3ee0f70e9e4ebbae347c268ece8c15":{
      "scriptId":"u71"},
    "9eb724835e9047e9ba97bc48a7136fba":{
      "scriptId":"u72"},
    "ee3ba53de6f244bf8de90c94749bf9f5":{
      "scriptId":"u73"},
    "62099559ab1a45208d95f894bcdf0798":{
      "scriptId":"u74"},
    "d7169d515c8642ba882ceceb8b7e3648":{
      "scriptId":"u75"},
    "a7005ea4ec844597ac056cfcba6c576d":{
      "scriptId":"u76"},
    "440a1b303c5d48dbb2df6449aaa8ff8e":{
      "scriptId":"u77"},
    "f3de0a7ecf7c482fb2e04f3338f3d7aa":{
      "scriptId":"u78"},
    "8e02818f14e344bb99d930c4aa64b5b2":{
      "scriptId":"u79"},
    "70b513c1133b4cc484e91703e6e5a39c":{
      "scriptId":"u80"},
    "93de88bea8574ad98469a9e698e44e86":{
      "scriptId":"u81"},
    "e93cf2aaea0c40b296b2696de523acd7":{
      "scriptId":"u82"},
    "c4c48aee53304cd4a079ac191e7c9036":{
      "scriptId":"u83"},
    "b2fd9e0ae048403da576448ab61035fc":{
      "scriptId":"u84"},
    "90133a309460446fb8b3592f27a6d860":{
      "scriptId":"u85"},
    "e24d40c775c04e8c8adab7a43a6fbeab":{
      "scriptId":"u86"},
    "55e1e5816e05404c8b1de1df8f277726":{
      "scriptId":"u87"},
    "66d80d3369d84f4bbcbd53e5fe162882":{
      "scriptId":"u88"},
    "10b461ef2e8a4d09bc1ce5db66c7b7e5":{
      "scriptId":"u89"},
    "58333d1149e64c7e880e44bfb2bf0c8f":{
      "scriptId":"u90"},
    "5eaec3cda9ac4138ae66bec900b870dc":{
      "scriptId":"u91"},
    "17ca9f8986c74275b90b301c29e7971b":{
      "scriptId":"u92"},
    "595f455376234772b246378d8de6de3c":{
      "scriptId":"u93"},
    "64cb0777fe704f14b9c15ccff4db2620":{
      "scriptId":"u94"},
    "a73ba12866554f90881ad5a585afbbf3":{
      "scriptId":"u95"},
    "410073dbbfa34ed48ce4006dd7509cef":{
      "scriptId":"u96"},
    "b905d8d7e6ad4ca89d63a6c0840dce00":{
      "scriptId":"u97"},
    "3333fdedf7694c3f94d3219d20bc99ec":{
      "scriptId":"u98"},
    "e26dc6fe5655499fb5035f72f19952ad":{
      "scriptId":"u99"}}});