$axure.loadCurrentPage({
  "url":"供应商编辑报价单.html",
  "generationDate":new Date(1462500150820.06),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1f3ef26407cb4a5e812e518f67a02e8f",
    "type":"Axure:Page",
    "name":"供应商编辑报价单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c42f95ad644b456b9807f8a794e5650c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":130},
            "size":{
              "width":1060,
              "height":1150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff9ed9acbcb34f7aad98c5456c996759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":130},
                "size":{
                  "width":1060,
                  "height":1150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u0.png"}},
{
          "id":"1475bdd78ca047ada6313a2099628441",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009966,
              "opacity":1},
            "location":{
              "x":552,
              "y":140},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"103a92e091ae4bb4a4e736523bcfe3f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009966,
                  "opacity":1},
                "location":{
                  "x":552,
                  "y":140},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"def2240d5ac4491aa4fc49d5fa91dc10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":220},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"559853a80cc444ebb35324a534e3b95c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":220},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f8ad56681db4bbe89908c89120b3ffd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":110,
              "y":261},
            "size":{
              "width":1020,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c38a059da3346e9b3836cef9180af01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":110,
                  "y":261},
                "size":{
                  "width":1020,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u6.png"}},
{
          "id":"c9e05c5b46da4a358ef3a28a0947d583",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":120,
              "y":277},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afabb70e1a3f4b29bef139fef9e79e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":120,
                  "y":277},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c89a792f477a492d8988bba07d82a157",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":261,
              "y":277},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"561c7b32ea564151bb0952c73b2f9abe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":261,
                  "y":277},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fbc417a2004454bbb336fffb4cbe9ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":403,
              "y":277},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d85f16b94a047a2aaee3d5d8a4977d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":403,
                  "y":277},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0efbfd0831c549d5923787be3034d9f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":527,
              "y":277},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a0d35e4b9644619e2c9abfc3c52472",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":527,
                  "y":277},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bffbf95ada244c082236a705217e738",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":656,
              "y":277},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ecdb9408874a1f9e8921b4c0251743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":656,
                  "y":277},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9ce8351a30a48eab84b1d6d55f85472",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":789,
              "y":277},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29ca34de24fc4d2fb41ca238379958aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":789,
                  "y":277},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b806a03b2ec34cdc8b8e57ff643de1a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":908,
              "y":277},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f504866acb14b278b73d09a2f8d1126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":908,
                  "y":277},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82064b9876d34da3a0173c6142911e05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":1020,
              "y":277},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5f0ec2a0e3b48658995bba625b752b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":1020,
                  "y":277},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cede9af2e4bf4785bd1bf289f5c5a56a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":311},
            "size":{
              "width":1020,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e535301f07f4485c88f1bb83448a247b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":311},
                "size":{
                  "width":1020,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u24.png"}},
{
          "id":"9b93c68733e447bd9949548c2afc95f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":120,
              "y":341},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04f2d4a601bb4284833a337563066af1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":120,
                  "y":341},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28e8221d3fe843639e21e2e7b4268541",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":257,
              "y":331},
            "size":{
              "width":120,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9363c9462b234c1f9365e41ca2752ade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":257,
                  "y":331},
                "size":{
                  "width":120,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e95029bab1b648439da3298cacf05442",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":393,
              "y":341},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f73d934b603b41c1844dcb6684ba152e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":393,
                  "y":341},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5c397ba7c5148caa542eb239ab1e69a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":513,
              "y":341},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc4925f16177472caf5733f6e30b6a2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":513,
                  "y":341},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f85b5982dacf42a5bc7e25e2ab87b46a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":680,
              "y":341},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9aebefa175314651a99550faa1ea7b71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":680,
                  "y":341},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75d31087d49b40a2ae73eb01b3317953",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":643,
              "y":338},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d610d6f0aa6c49edb592f87388783408",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":338},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4067a3e2d8e54eb0b6745f97e9801d65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":860,
              "y":341},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69ac087ecc0e43488f016f0a3fcea1bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":860,
                  "y":341},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"279e866165ea42dfa84248f98cabba6a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":928,
              "y":338},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b19a34d1b35c4fcc92418429afe8a04e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":391},
            "size":{
              "width":1020,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a761a72b57ec447da024e0dc2204ec8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":391},
                "size":{
                  "width":1020,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u24.png"}},
{
          "id":"40717696c7f940709c1cf399b99f0b8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":870,
              "y":481},
            "size":{
              "width":260,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c551bc895e4b20b8a209432e946c40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":870,
                  "y":481},
                "size":{
                  "width":260,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0523a9cef52c435bbbc4fa8c46c183df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":257,
              "y":411},
            "size":{
              "width":120,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ee98d47baf244bab19db07d7763f700",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":257,
                  "y":411},
                "size":{
                  "width":120,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4235f04871fb4a0896413499a3911d15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":393,
              "y":421},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef762c2823e5468e909e4c66a1c0e3f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":393,
                  "y":421},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3dc10b5021e4f2fad92cb253c8292e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":513,
              "y":421},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae09dba3e69f4090a3c06c1a7ea5b75e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":513,
                  "y":421},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a14d3c0db444838a92323446f273326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":680,
              "y":421},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"beeb63d920e24c1b932383fadb9df1d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":680,
                  "y":421},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da4d8d4765ea40b2a1bb3455874ec85e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":643,
              "y":418},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4234ea1af23f4fbc82f899380bc9d52d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":418},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"d20c530fd4434f43a9be0319a0f6f5e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":860,
              "y":421},
            "size":{
              "width":40,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc691513aeb421ca94611b4757a6e83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":860,
                  "y":421},
                "size":{
                  "width":40,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b6693175e3a4147b3e107aab941b8af",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":928,
              "y":418},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c4f7ab11d9fe4b83879d113771601e2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":120,
              "y":418},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59fe1480bb774b6a8036686bdab840bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":120,
                  "y":418},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6c02e1945b9441482961382a40c2ca5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":541},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f7e682ef80453f89f40e72205790cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":541},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6a70563e5904936b0d3e5927460c789",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":601},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21b1289f15014316a6d2e7e5a2bd7832",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":601},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a64d54239914c6486cb0038f1018b8f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":521},
            "size":{
              "width":1060,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/供应商编辑报价单/u64_line.png"}},
{
          "id":"13ccdda02cbe465f845d7cf5809ea36d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":245,
              "y":601},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfc26a9a71b848dca4dd1bfdaf3a3580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":245,
                  "y":601},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"7ef07a2bbcb14ea3925ba06184c0333b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":360,
              "y":601},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6b73861924846ac9408945e5a7c26c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":360,
                  "y":601},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"b76297a96c044eb4808c3877602d3725",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":475,
              "y":601},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ae4b8565a8341059ebbe4115e43e6fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":475,
                  "y":601},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"2f43ce62bf57458fac2b30798099c680",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":590,
              "y":601},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57673b360a424654b449a3db90e4c405",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":590,
                  "y":601},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"f006bc6a6fbc4fa8840d99c3f3a26cae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":640},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a245cbeabd22427789020f739ff95882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":640},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23c3b24925cc48f6875469614a4fa588",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":245,
              "y":640},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f00e40fdd15e47428addbe94e9d7fb7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":245,
                  "y":640},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"ecac583821af4b47be9a3ddb0ef0e7d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":680},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6b4534da83b4d4d85e55c5aaddceade",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":680},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0cff5c9baa054f7db77d94e20d9548d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":245,
              "y":680},
            "size":{
              "width":85,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1f3bd5463b8410a81a0a2240703c466",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":245,
                  "y":680},
                "size":{
                  "width":85,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5b489974427e4b42925661d00a8c38f6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":680},
            "size":{
              "width":50,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8f2cd6f969d14694ad33c4c404cba3db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":393,
              "y":681},
            "size":{
              "width":140,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea901b20498e49aca848ea511912a95d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":393,
                  "y":681},
                "size":{
                  "width":140,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e938c552fbc41edb9f64840a5ebe7fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":463,
              "y":676},
            "size":{
              "width":11,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"329e0a626d7e445a9618190fbef0f266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":463,
                  "y":676},
                "size":{
                  "width":11,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u84.png"}},
{
          "id":"ef3bbaa4a5f240f28615ddf972e2d9ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":681},
            "size":{
              "width":11,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d11c4d2e3941f782cdd2e7cd604051",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":681},
                "size":{
                  "width":11,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u84.png"}},
{
          "id":"8b10c9620da345c89fbcef0f28356858",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":720},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49a4f5894dbb45fbbd3daf49e666bde4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":720},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c8d9646bd9444a09d71c4a25ad73b0d",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":258,
              "y":720},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f1fcf5666f141d7a8e058a29d41cb12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":258,
                  "y":720},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"504846638c7b4f4cabb80f2b69cbec0e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":365,
              "y":720},
            "size":{
              "width":100,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d39e3fa83c44e69ba3cf10cfca70c81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":365,
                  "y":720},
                "size":{
                  "width":100,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"242684b6b3644389927c97d07238de86",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":472,
              "y":720},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cf30a13867e479b8b9298c0735be905",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":472,
                  "y":720},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"8904972d3ad44379bf05a600972b42c4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":610,
              "y":720},
            "size":{
              "width":220,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66ec3e692d004cb2913e9d955e0770c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":610,
                  "y":720},
                "size":{
                  "width":220,
                  "height":19}},
              "adaptiveStyles":{
}}]},
{
          "id":"ff6323e8d4fc4ad294b6e2187b3bfba2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":780},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41275716c36a4d7f99423ac97df802b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":780},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b1de482c692e4f689434c8c88e2c5a15",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":760},
            "size":{
              "width":1060,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/供应商编辑报价单/u64_line.png"}},
{
          "id":"04da28d08adb4e30a1e50380d2d4b96b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":820},
            "size":{
              "width":150,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc8442476c07402fadc8e7c88d96815b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":820},
                "size":{
                  "width":150,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aa21f31ca9241f59b581c6a507637fa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":818},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4633aad945164ef394efc47110c191ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":490,
              "y":821},
            "size":{
              "width":50,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2818ee21a3d34852a74730123c79ffe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":490,
                  "y":821},
                "size":{
                  "width":50,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40dd53c530ed4cbfbadfc034bf487a33",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":130,
              "y":861},
            "size":{
              "width":150,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09e9a193708b41868a01508653ea4dff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":130,
                  "y":861},
                "size":{
                  "width":150,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7b8c84d1f254195956ffd69093c5968",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":853},
            "size":{
              "width":200,
              "height":35}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 日期",
                      "objectsToFades":[{
                          "objectPath":["f515cfc5eff94eeea24f11e2af8daceb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onLostFocus":{
              "description":"OnLostFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 日期",
                      "objectsToFades":[{
                          "objectPath":["f515cfc5eff94eeea24f11e2af8daceb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"dc208a6debad4b14ab8997a94590b017",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":858},
            "size":{
              "width":22,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97776f23d04a4784a5b96957a0027c74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":858},
                "size":{
                  "width":22,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u109.png"}},
{
          "id":"79b8daaf60e24d088f3dd99283c83852",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":139,
              "y":901},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80aff8a92a57497a926624360e913353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":139,
                  "y":901},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d4f5c803df884085b001d75864cf407b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":280,
              "y":901},
            "size":{
              "width":150,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e6625c33442408583eab482434755d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":901},
                "size":{
                  "width":150,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cf73400240b48ec905fbd8d2e70e2e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":139,
              "y":941},
            "size":{
              "width":130,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13e6567159db4b79ab2a3ad62ebfe315",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":139,
                  "y":941},
                "size":{
                  "width":130,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27f6e8b749d247e1ad3e0e491677425d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":950},
            "size":{
              "width":414,
              "height":160}},
          "adaptiveStyles":{
}},
{
          "id":"ff8b3a2a7f1d4ab6bda70844b023db4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":527,
              "y":1180},
            "size":{
              "width":170,
              "height":40},
            "cornerRadiusTopLeft":"7"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"135e81c7841d4931ac108af7c1673c38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":527,
                  "y":1180},
                "size":{
                  "width":170,
                  "height":40},
                "cornerRadiusTopLeft":"7"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/供应商编辑报价单/u118.png"}},
{
          "id":"f515cfc5eff94eeea24f11e2af8daceb",
          "label":"日期",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":269,
              "y":888},
            "size":{
              "width":243,
              "height":221},
            "visible":false,
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1057970d976946f4bb02681e8b84b2e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":269,
                  "y":888},
                "size":{
                  "width":243,
                  "height":221},
                "visible":false,
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 This",
                      "objectsToFades":[{
                          "objectPath":["f515cfc5eff94eeea24f11e2af8daceb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/供应商编辑报价单/日期_u120.png"}},
{
          "id":"c5a150079d754451834b8600ffa781ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":569,
              "y":168},
            "size":{
              "width":120,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd86815c63634190a41f4f516a4e2fff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":569,
                  "y":168},
                "size":{
                  "width":120,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c945b3ef9e14d6ab0cd2befa6fe5e9c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":90},
            "size":{
              "width":1370,
              "height":10},
            "borderWidth":"3",
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/供应商编辑报价单/u124_line.png"}},
{
          "id":"84dc118a67b14ad7b2048272b6db8ec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":410,
              "y":36},
            "size":{
              "width":380,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0373c7f80b9477287f168e465007f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":410,
                  "y":36},
                "size":{
                  "width":380,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c42f95ad644b456b9807f8a794e5650c":{
      "scriptId":"u0"},
    "ff9ed9acbcb34f7aad98c5456c996759":{
      "scriptId":"u1"},
    "1475bdd78ca047ada6313a2099628441":{
      "scriptId":"u2"},
    "103a92e091ae4bb4a4e736523bcfe3f1":{
      "scriptId":"u3"},
    "def2240d5ac4491aa4fc49d5fa91dc10":{
      "scriptId":"u4"},
    "559853a80cc444ebb35324a534e3b95c":{
      "scriptId":"u5"},
    "9f8ad56681db4bbe89908c89120b3ffd":{
      "scriptId":"u6"},
    "5c38a059da3346e9b3836cef9180af01":{
      "scriptId":"u7"},
    "c9e05c5b46da4a358ef3a28a0947d583":{
      "scriptId":"u8"},
    "afabb70e1a3f4b29bef139fef9e79e40":{
      "scriptId":"u9"},
    "c89a792f477a492d8988bba07d82a157":{
      "scriptId":"u10"},
    "561c7b32ea564151bb0952c73b2f9abe":{
      "scriptId":"u11"},
    "3fbc417a2004454bbb336fffb4cbe9ed":{
      "scriptId":"u12"},
    "0d85f16b94a047a2aaee3d5d8a4977d9":{
      "scriptId":"u13"},
    "0efbfd0831c549d5923787be3034d9f9":{
      "scriptId":"u14"},
    "a9a0d35e4b9644619e2c9abfc3c52472":{
      "scriptId":"u15"},
    "6bffbf95ada244c082236a705217e738":{
      "scriptId":"u16"},
    "91ecdb9408874a1f9e8921b4c0251743":{
      "scriptId":"u17"},
    "a9ce8351a30a48eab84b1d6d55f85472":{
      "scriptId":"u18"},
    "29ca34de24fc4d2fb41ca238379958aa":{
      "scriptId":"u19"},
    "b806a03b2ec34cdc8b8e57ff643de1a0":{
      "scriptId":"u20"},
    "1f504866acb14b278b73d09a2f8d1126":{
      "scriptId":"u21"},
    "82064b9876d34da3a0173c6142911e05":{
      "scriptId":"u22"},
    "e5f0ec2a0e3b48658995bba625b752b9":{
      "scriptId":"u23"},
    "cede9af2e4bf4785bd1bf289f5c5a56a":{
      "scriptId":"u24"},
    "e535301f07f4485c88f1bb83448a247b":{
      "scriptId":"u25"},
    "9b93c68733e447bd9949548c2afc95f9":{
      "scriptId":"u26"},
    "04f2d4a601bb4284833a337563066af1":{
      "scriptId":"u27"},
    "28e8221d3fe843639e21e2e7b4268541":{
      "scriptId":"u28"},
    "9363c9462b234c1f9365e41ca2752ade":{
      "scriptId":"u29"},
    "e95029bab1b648439da3298cacf05442":{
      "scriptId":"u30"},
    "f73d934b603b41c1844dcb6684ba152e":{
      "scriptId":"u31"},
    "f5c397ba7c5148caa542eb239ab1e69a":{
      "scriptId":"u32"},
    "bc4925f16177472caf5733f6e30b6a2c":{
      "scriptId":"u33"},
    "f85b5982dacf42a5bc7e25e2ab87b46a":{
      "scriptId":"u34"},
    "9aebefa175314651a99550faa1ea7b71":{
      "scriptId":"u35"},
    "75d31087d49b40a2ae73eb01b3317953":{
      "scriptId":"u36"},
    "d610d6f0aa6c49edb592f87388783408":{
      "scriptId":"u37"},
    "4067a3e2d8e54eb0b6745f97e9801d65":{
      "scriptId":"u38"},
    "69ac087ecc0e43488f016f0a3fcea1bc":{
      "scriptId":"u39"},
    "279e866165ea42dfa84248f98cabba6a":{
      "scriptId":"u40"},
    "b19a34d1b35c4fcc92418429afe8a04e":{
      "scriptId":"u41"},
    "a761a72b57ec447da024e0dc2204ec8a":{
      "scriptId":"u42"},
    "40717696c7f940709c1cf399b99f0b8a":{
      "scriptId":"u43"},
    "b2c551bc895e4b20b8a209432e946c40":{
      "scriptId":"u44"},
    "0523a9cef52c435bbbc4fa8c46c183df":{
      "scriptId":"u45"},
    "1ee98d47baf244bab19db07d7763f700":{
      "scriptId":"u46"},
    "4235f04871fb4a0896413499a3911d15":{
      "scriptId":"u47"},
    "ef762c2823e5468e909e4c66a1c0e3f0":{
      "scriptId":"u48"},
    "f3dc10b5021e4f2fad92cb253c8292e4":{
      "scriptId":"u49"},
    "ae09dba3e69f4090a3c06c1a7ea5b75e":{
      "scriptId":"u50"},
    "3a14d3c0db444838a92323446f273326":{
      "scriptId":"u51"},
    "beeb63d920e24c1b932383fadb9df1d7":{
      "scriptId":"u52"},
    "da4d8d4765ea40b2a1bb3455874ec85e":{
      "scriptId":"u53"},
    "4234ea1af23f4fbc82f899380bc9d52d":{
      "scriptId":"u54"},
    "d20c530fd4434f43a9be0319a0f6f5e2":{
      "scriptId":"u55"},
    "3cc691513aeb421ca94611b4757a6e83":{
      "scriptId":"u56"},
    "1b6693175e3a4147b3e107aab941b8af":{
      "scriptId":"u57"},
    "c4f7ab11d9fe4b83879d113771601e2d":{
      "scriptId":"u58"},
    "59fe1480bb774b6a8036686bdab840bc":{
      "scriptId":"u59"},
    "d6c02e1945b9441482961382a40c2ca5":{
      "scriptId":"u60"},
    "61f7e682ef80453f89f40e72205790cb":{
      "scriptId":"u61"},
    "a6a70563e5904936b0d3e5927460c789":{
      "scriptId":"u62"},
    "21b1289f15014316a6d2e7e5a2bd7832":{
      "scriptId":"u63"},
    "8a64d54239914c6486cb0038f1018b8f":{
      "scriptId":"u64"},
    "13ccdda02cbe465f845d7cf5809ea36d":{
      "scriptId":"u65"},
    "cfc26a9a71b848dca4dd1bfdaf3a3580":{
      "scriptId":"u66"},
    "7ef07a2bbcb14ea3925ba06184c0333b":{
      "scriptId":"u67"},
    "f6b73861924846ac9408945e5a7c26c3":{
      "scriptId":"u68"},
    "b76297a96c044eb4808c3877602d3725":{
      "scriptId":"u69"},
    "2ae4b8565a8341059ebbe4115e43e6fa":{
      "scriptId":"u70"},
    "2f43ce62bf57458fac2b30798099c680":{
      "scriptId":"u71"},
    "57673b360a424654b449a3db90e4c405":{
      "scriptId":"u72"},
    "f006bc6a6fbc4fa8840d99c3f3a26cae":{
      "scriptId":"u73"},
    "a245cbeabd22427789020f739ff95882":{
      "scriptId":"u74"},
    "23c3b24925cc48f6875469614a4fa588":{
      "scriptId":"u75"},
    "f00e40fdd15e47428addbe94e9d7fb7c":{
      "scriptId":"u76"},
    "ecac583821af4b47be9a3ddb0ef0e7d3":{
      "scriptId":"u77"},
    "f6b4534da83b4d4d85e55c5aaddceade":{
      "scriptId":"u78"},
    "0cff5c9baa054f7db77d94e20d9548d1":{
      "scriptId":"u79"},
    "f1f3bd5463b8410a81a0a2240703c466":{
      "scriptId":"u80"},
    "5b489974427e4b42925661d00a8c38f6":{
      "scriptId":"u81"},
    "8f2cd6f969d14694ad33c4c404cba3db":{
      "scriptId":"u82"},
    "ea901b20498e49aca848ea511912a95d":{
      "scriptId":"u83"},
    "1e938c552fbc41edb9f64840a5ebe7fc":{
      "scriptId":"u84"},
    "329e0a626d7e445a9618190fbef0f266":{
      "scriptId":"u85"},
    "ef3bbaa4a5f240f28615ddf972e2d9ef":{
      "scriptId":"u86"},
    "19d11c4d2e3941f782cdd2e7cd604051":{
      "scriptId":"u87"},
    "8b10c9620da345c89fbcef0f28356858":{
      "scriptId":"u88"},
    "49a4f5894dbb45fbbd3daf49e666bde4":{
      "scriptId":"u89"},
    "7c8d9646bd9444a09d71c4a25ad73b0d":{
      "scriptId":"u90"},
    "8f1fcf5666f141d7a8e058a29d41cb12":{
      "scriptId":"u91"},
    "504846638c7b4f4cabb80f2b69cbec0e":{
      "scriptId":"u92"},
    "0d39e3fa83c44e69ba3cf10cfca70c81":{
      "scriptId":"u93"},
    "242684b6b3644389927c97d07238de86":{
      "scriptId":"u94"},
    "7cf30a13867e479b8b9298c0735be905":{
      "scriptId":"u95"},
    "8904972d3ad44379bf05a600972b42c4":{
      "scriptId":"u96"},
    "66ec3e692d004cb2913e9d955e0770c8":{
      "scriptId":"u97"},
    "ff6323e8d4fc4ad294b6e2187b3bfba2":{
      "scriptId":"u98"},
    "41275716c36a4d7f99423ac97df802b2":{
      "scriptId":"u99"},
    "b1de482c692e4f689434c8c88e2c5a15":{
      "scriptId":"u100"},
    "04da28d08adb4e30a1e50380d2d4b96b":{
      "scriptId":"u101"},
    "fc8442476c07402fadc8e7c88d96815b":{
      "scriptId":"u102"},
    "9aa21f31ca9241f59b581c6a507637fa":{
      "scriptId":"u103"},
    "4633aad945164ef394efc47110c191ec":{
      "scriptId":"u104"},
    "2818ee21a3d34852a74730123c79ffe5":{
      "scriptId":"u105"},
    "40dd53c530ed4cbfbadfc034bf487a33":{
      "scriptId":"u106"},
    "09e9a193708b41868a01508653ea4dff":{
      "scriptId":"u107"},
    "e7b8c84d1f254195956ffd69093c5968":{
      "scriptId":"u108"},
    "dc208a6debad4b14ab8997a94590b017":{
      "scriptId":"u109"},
    "97776f23d04a4784a5b96957a0027c74":{
      "scriptId":"u110"},
    "79b8daaf60e24d088f3dd99283c83852":{
      "scriptId":"u111"},
    "80aff8a92a57497a926624360e913353":{
      "scriptId":"u112"},
    "d4f5c803df884085b001d75864cf407b":{
      "scriptId":"u113"},
    "5e6625c33442408583eab482434755d1":{
      "scriptId":"u114"},
    "2cf73400240b48ec905fbd8d2e70e2e9":{
      "scriptId":"u115"},
    "13e6567159db4b79ab2a3ad62ebfe315":{
      "scriptId":"u116"},
    "27f6e8b749d247e1ad3e0e491677425d":{
      "scriptId":"u117"},
    "ff8b3a2a7f1d4ab6bda70844b023db4d":{
      "scriptId":"u118"},
    "135e81c7841d4931ac108af7c1673c38":{
      "scriptId":"u119"},
    "f515cfc5eff94eeea24f11e2af8daceb":{
      "scriptId":"u120"},
    "1057970d976946f4bb02681e8b84b2e6":{
      "scriptId":"u121"},
    "c5a150079d754451834b8600ffa781ba":{
      "scriptId":"u122"},
    "fd86815c63634190a41f4f516a4e2fff":{
      "scriptId":"u123"},
    "8c945b3ef9e14d6ab0cd2befa6fe5e9c":{
      "scriptId":"u124"},
    "84dc118a67b14ad7b2048272b6db8ec7":{
      "scriptId":"u125"},
    "f0373c7f80b9477287f168e465007f62":{
      "scriptId":"u126"}}});